/*
 * salesforce api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ObjectInfoUrls;

/**
 * ObjectInfoSobjects
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-01T18:23:34.688259300+08:00[Asia/Shanghai]")
public class ObjectInfoSobjects {
  public static final String SERIALIZED_NAME_ACTIVATEABLE = "activateable";
  @SerializedName(SERIALIZED_NAME_ACTIVATEABLE)
  private Boolean activateable;

  public static final String SERIALIZED_NAME_ASSOCIATE_ENTITY_TYPE = "associateEntityType";
  @SerializedName(SERIALIZED_NAME_ASSOCIATE_ENTITY_TYPE)
  private String associateEntityType;

  public static final String SERIALIZED_NAME_ASSOCIATE_PARENT_ENTITY = "associateParentEntity";
  @SerializedName(SERIALIZED_NAME_ASSOCIATE_PARENT_ENTITY)
  private String associateParentEntity;

  public static final String SERIALIZED_NAME_CREATEABLE = "createable";
  @SerializedName(SERIALIZED_NAME_CREATEABLE)
  private Boolean createable;

  public static final String SERIALIZED_NAME_CUSTOM = "custom";
  @SerializedName(SERIALIZED_NAME_CUSTOM)
  private Boolean custom;

  public static final String SERIALIZED_NAME_CUSTOM_SETTING = "customSetting";
  @SerializedName(SERIALIZED_NAME_CUSTOM_SETTING)
  private Boolean customSetting;

  public static final String SERIALIZED_NAME_DEEP_CLONEABLE = "deepCloneable";
  @SerializedName(SERIALIZED_NAME_DEEP_CLONEABLE)
  private Boolean deepCloneable;

  public static final String SERIALIZED_NAME_DELETABLE = "deletable";
  @SerializedName(SERIALIZED_NAME_DELETABLE)
  private Boolean deletable;

  public static final String SERIALIZED_NAME_DEPRECATED_AND_HIDDEN = "deprecatedAndHidden";
  @SerializedName(SERIALIZED_NAME_DEPRECATED_AND_HIDDEN)
  private Boolean deprecatedAndHidden;

  public static final String SERIALIZED_NAME_FEED_ENABLED = "feedEnabled";
  @SerializedName(SERIALIZED_NAME_FEED_ENABLED)
  private Boolean feedEnabled;

  public static final String SERIALIZED_NAME_HAS_SUBTYPES = "hasSubtypes";
  @SerializedName(SERIALIZED_NAME_HAS_SUBTYPES)
  private Boolean hasSubtypes;

  public static final String SERIALIZED_NAME_IS_INTERFACE = "isInterface";
  @SerializedName(SERIALIZED_NAME_IS_INTERFACE)
  private Boolean isInterface;

  public static final String SERIALIZED_NAME_IS_SUBTYPE = "isSubtype";
  @SerializedName(SERIALIZED_NAME_IS_SUBTYPE)
  private Boolean isSubtype;

  public static final String SERIALIZED_NAME_KEY_PREFIX = "keyPrefix";
  @SerializedName(SERIALIZED_NAME_KEY_PREFIX)
  private String keyPrefix;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_LABEL_PLURAL = "labelPlural";
  @SerializedName(SERIALIZED_NAME_LABEL_PLURAL)
  private String labelPlural;

  public static final String SERIALIZED_NAME_LAYOUTABLE = "layoutable";
  @SerializedName(SERIALIZED_NAME_LAYOUTABLE)
  private Boolean layoutable;

  public static final String SERIALIZED_NAME_MERGEABLE = "mergeable";
  @SerializedName(SERIALIZED_NAME_MERGEABLE)
  private Boolean mergeable;

  public static final String SERIALIZED_NAME_MRU_ENABLED = "mruEnabled";
  @SerializedName(SERIALIZED_NAME_MRU_ENABLED)
  private Boolean mruEnabled;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_QUERYABLE = "queryable";
  @SerializedName(SERIALIZED_NAME_QUERYABLE)
  private Boolean queryable;

  public static final String SERIALIZED_NAME_REPLICATEABLE = "replicateable";
  @SerializedName(SERIALIZED_NAME_REPLICATEABLE)
  private Boolean replicateable;

  public static final String SERIALIZED_NAME_RETRIEVEABLE = "retrieveable";
  @SerializedName(SERIALIZED_NAME_RETRIEVEABLE)
  private Boolean retrieveable;

  public static final String SERIALIZED_NAME_SEARCHABLE = "searchable";
  @SerializedName(SERIALIZED_NAME_SEARCHABLE)
  private Boolean searchable;

  public static final String SERIALIZED_NAME_TRIGGERABLE = "triggerable";
  @SerializedName(SERIALIZED_NAME_TRIGGERABLE)
  private Boolean triggerable;

  public static final String SERIALIZED_NAME_UNDELETABLE = "undeletable";
  @SerializedName(SERIALIZED_NAME_UNDELETABLE)
  private Boolean undeletable;

  public static final String SERIALIZED_NAME_UPDATEABLE = "updateable";
  @SerializedName(SERIALIZED_NAME_UPDATEABLE)
  private Boolean updateable;

  public static final String SERIALIZED_NAME_URLS = "urls";
  @SerializedName(SERIALIZED_NAME_URLS)
  private ObjectInfoUrls urls;


  public ObjectInfoSobjects activateable(Boolean activateable) {
    
    this.activateable = activateable;
    return this;
  }

   /**
   * Get activateable
   * @return activateable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getActivateable() {
    return activateable;
  }


  public void setActivateable(Boolean activateable) {
    this.activateable = activateable;
  }


  public ObjectInfoSobjects associateEntityType(String associateEntityType) {
    
    this.associateEntityType = associateEntityType;
    return this;
  }

   /**
   * Get associateEntityType
   * @return associateEntityType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getAssociateEntityType() {
    return associateEntityType;
  }


  public void setAssociateEntityType(String associateEntityType) {
    this.associateEntityType = associateEntityType;
  }


  public ObjectInfoSobjects associateParentEntity(String associateParentEntity) {
    
    this.associateParentEntity = associateParentEntity;
    return this;
  }

   /**
   * Get associateParentEntity
   * @return associateParentEntity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getAssociateParentEntity() {
    return associateParentEntity;
  }


  public void setAssociateParentEntity(String associateParentEntity) {
    this.associateParentEntity = associateParentEntity;
  }


  public ObjectInfoSobjects createable(Boolean createable) {
    
    this.createable = createable;
    return this;
  }

   /**
   * Get createable
   * @return createable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCreateable() {
    return createable;
  }


  public void setCreateable(Boolean createable) {
    this.createable = createable;
  }


  public ObjectInfoSobjects custom(Boolean custom) {
    
    this.custom = custom;
    return this;
  }

   /**
   * Get custom
   * @return custom
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCustom() {
    return custom;
  }


  public void setCustom(Boolean custom) {
    this.custom = custom;
  }


  public ObjectInfoSobjects customSetting(Boolean customSetting) {
    
    this.customSetting = customSetting;
    return this;
  }

   /**
   * Get customSetting
   * @return customSetting
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCustomSetting() {
    return customSetting;
  }


  public void setCustomSetting(Boolean customSetting) {
    this.customSetting = customSetting;
  }


  public ObjectInfoSobjects deepCloneable(Boolean deepCloneable) {
    
    this.deepCloneable = deepCloneable;
    return this;
  }

   /**
   * Get deepCloneable
   * @return deepCloneable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDeepCloneable() {
    return deepCloneable;
  }


  public void setDeepCloneable(Boolean deepCloneable) {
    this.deepCloneable = deepCloneable;
  }


  public ObjectInfoSobjects deletable(Boolean deletable) {
    
    this.deletable = deletable;
    return this;
  }

   /**
   * Get deletable
   * @return deletable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDeletable() {
    return deletable;
  }


  public void setDeletable(Boolean deletable) {
    this.deletable = deletable;
  }


  public ObjectInfoSobjects deprecatedAndHidden(Boolean deprecatedAndHidden) {
    
    this.deprecatedAndHidden = deprecatedAndHidden;
    return this;
  }

   /**
   * Get deprecatedAndHidden
   * @return deprecatedAndHidden
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDeprecatedAndHidden() {
    return deprecatedAndHidden;
  }


  public void setDeprecatedAndHidden(Boolean deprecatedAndHidden) {
    this.deprecatedAndHidden = deprecatedAndHidden;
  }


  public ObjectInfoSobjects feedEnabled(Boolean feedEnabled) {
    
    this.feedEnabled = feedEnabled;
    return this;
  }

   /**
   * Get feedEnabled
   * @return feedEnabled
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getFeedEnabled() {
    return feedEnabled;
  }


  public void setFeedEnabled(Boolean feedEnabled) {
    this.feedEnabled = feedEnabled;
  }


  public ObjectInfoSobjects hasSubtypes(Boolean hasSubtypes) {
    
    this.hasSubtypes = hasSubtypes;
    return this;
  }

   /**
   * Get hasSubtypes
   * @return hasSubtypes
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getHasSubtypes() {
    return hasSubtypes;
  }


  public void setHasSubtypes(Boolean hasSubtypes) {
    this.hasSubtypes = hasSubtypes;
  }


  public ObjectInfoSobjects isInterface(Boolean isInterface) {
    
    this.isInterface = isInterface;
    return this;
  }

   /**
   * Get isInterface
   * @return isInterface
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getIsInterface() {
    return isInterface;
  }


  public void setIsInterface(Boolean isInterface) {
    this.isInterface = isInterface;
  }


  public ObjectInfoSobjects isSubtype(Boolean isSubtype) {
    
    this.isSubtype = isSubtype;
    return this;
  }

   /**
   * Get isSubtype
   * @return isSubtype
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getIsSubtype() {
    return isSubtype;
  }


  public void setIsSubtype(Boolean isSubtype) {
    this.isSubtype = isSubtype;
  }


  public ObjectInfoSobjects keyPrefix(String keyPrefix) {
    
    this.keyPrefix = keyPrefix;
    return this;
  }

   /**
   * Get keyPrefix
   * @return keyPrefix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getKeyPrefix() {
    return keyPrefix;
  }


  public void setKeyPrefix(String keyPrefix) {
    this.keyPrefix = keyPrefix;
  }


  public ObjectInfoSobjects label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public ObjectInfoSobjects labelPlural(String labelPlural) {
    
    this.labelPlural = labelPlural;
    return this;
  }

   /**
   * Get labelPlural
   * @return labelPlural
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLabelPlural() {
    return labelPlural;
  }


  public void setLabelPlural(String labelPlural) {
    this.labelPlural = labelPlural;
  }


  public ObjectInfoSobjects layoutable(Boolean layoutable) {
    
    this.layoutable = layoutable;
    return this;
  }

   /**
   * Get layoutable
   * @return layoutable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getLayoutable() {
    return layoutable;
  }


  public void setLayoutable(Boolean layoutable) {
    this.layoutable = layoutable;
  }


  public ObjectInfoSobjects mergeable(Boolean mergeable) {
    
    this.mergeable = mergeable;
    return this;
  }

   /**
   * Get mergeable
   * @return mergeable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getMergeable() {
    return mergeable;
  }


  public void setMergeable(Boolean mergeable) {
    this.mergeable = mergeable;
  }


  public ObjectInfoSobjects mruEnabled(Boolean mruEnabled) {
    
    this.mruEnabled = mruEnabled;
    return this;
  }

   /**
   * Get mruEnabled
   * @return mruEnabled
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getMruEnabled() {
    return mruEnabled;
  }


  public void setMruEnabled(Boolean mruEnabled) {
    this.mruEnabled = mruEnabled;
  }


  public ObjectInfoSobjects name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ObjectInfoSobjects queryable(Boolean queryable) {
    
    this.queryable = queryable;
    return this;
  }

   /**
   * Get queryable
   * @return queryable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getQueryable() {
    return queryable;
  }


  public void setQueryable(Boolean queryable) {
    this.queryable = queryable;
  }


  public ObjectInfoSobjects replicateable(Boolean replicateable) {
    
    this.replicateable = replicateable;
    return this;
  }

   /**
   * Get replicateable
   * @return replicateable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getReplicateable() {
    return replicateable;
  }


  public void setReplicateable(Boolean replicateable) {
    this.replicateable = replicateable;
  }


  public ObjectInfoSobjects retrieveable(Boolean retrieveable) {
    
    this.retrieveable = retrieveable;
    return this;
  }

   /**
   * Get retrieveable
   * @return retrieveable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getRetrieveable() {
    return retrieveable;
  }


  public void setRetrieveable(Boolean retrieveable) {
    this.retrieveable = retrieveable;
  }


  public ObjectInfoSobjects searchable(Boolean searchable) {
    
    this.searchable = searchable;
    return this;
  }

   /**
   * Get searchable
   * @return searchable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getSearchable() {
    return searchable;
  }


  public void setSearchable(Boolean searchable) {
    this.searchable = searchable;
  }


  public ObjectInfoSobjects triggerable(Boolean triggerable) {
    
    this.triggerable = triggerable;
    return this;
  }

   /**
   * Get triggerable
   * @return triggerable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getTriggerable() {
    return triggerable;
  }


  public void setTriggerable(Boolean triggerable) {
    this.triggerable = triggerable;
  }


  public ObjectInfoSobjects undeletable(Boolean undeletable) {
    
    this.undeletable = undeletable;
    return this;
  }

   /**
   * Get undeletable
   * @return undeletable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getUndeletable() {
    return undeletable;
  }


  public void setUndeletable(Boolean undeletable) {
    this.undeletable = undeletable;
  }


  public ObjectInfoSobjects updateable(Boolean updateable) {
    
    this.updateable = updateable;
    return this;
  }

   /**
   * Get updateable
   * @return updateable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getUpdateable() {
    return updateable;
  }


  public void setUpdateable(Boolean updateable) {
    this.updateable = updateable;
  }


  public ObjectInfoSobjects urls(ObjectInfoUrls urls) {
    
    this.urls = urls;
    return this;
  }

   /**
   * Get urls
   * @return urls
  **/
  @ApiModelProperty(required = true, value = "")

  public ObjectInfoUrls getUrls() {
    return urls;
  }


  public void setUrls(ObjectInfoUrls urls) {
    this.urls = urls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectInfoSobjects objectInfoSobjects = (ObjectInfoSobjects) o;
    return Objects.equals(this.activateable, objectInfoSobjects.activateable) &&
        Objects.equals(this.associateEntityType, objectInfoSobjects.associateEntityType) &&
        Objects.equals(this.associateParentEntity, objectInfoSobjects.associateParentEntity) &&
        Objects.equals(this.createable, objectInfoSobjects.createable) &&
        Objects.equals(this.custom, objectInfoSobjects.custom) &&
        Objects.equals(this.customSetting, objectInfoSobjects.customSetting) &&
        Objects.equals(this.deepCloneable, objectInfoSobjects.deepCloneable) &&
        Objects.equals(this.deletable, objectInfoSobjects.deletable) &&
        Objects.equals(this.deprecatedAndHidden, objectInfoSobjects.deprecatedAndHidden) &&
        Objects.equals(this.feedEnabled, objectInfoSobjects.feedEnabled) &&
        Objects.equals(this.hasSubtypes, objectInfoSobjects.hasSubtypes) &&
        Objects.equals(this.isInterface, objectInfoSobjects.isInterface) &&
        Objects.equals(this.isSubtype, objectInfoSobjects.isSubtype) &&
        Objects.equals(this.keyPrefix, objectInfoSobjects.keyPrefix) &&
        Objects.equals(this.label, objectInfoSobjects.label) &&
        Objects.equals(this.labelPlural, objectInfoSobjects.labelPlural) &&
        Objects.equals(this.layoutable, objectInfoSobjects.layoutable) &&
        Objects.equals(this.mergeable, objectInfoSobjects.mergeable) &&
        Objects.equals(this.mruEnabled, objectInfoSobjects.mruEnabled) &&
        Objects.equals(this.name, objectInfoSobjects.name) &&
        Objects.equals(this.queryable, objectInfoSobjects.queryable) &&
        Objects.equals(this.replicateable, objectInfoSobjects.replicateable) &&
        Objects.equals(this.retrieveable, objectInfoSobjects.retrieveable) &&
        Objects.equals(this.searchable, objectInfoSobjects.searchable) &&
        Objects.equals(this.triggerable, objectInfoSobjects.triggerable) &&
        Objects.equals(this.undeletable, objectInfoSobjects.undeletable) &&
        Objects.equals(this.updateable, objectInfoSobjects.updateable) &&
        Objects.equals(this.urls, objectInfoSobjects.urls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activateable, associateEntityType, associateParentEntity, createable, custom, customSetting, deepCloneable, deletable, deprecatedAndHidden, feedEnabled, hasSubtypes, isInterface, isSubtype, keyPrefix, label, labelPlural, layoutable, mergeable, mruEnabled, name, queryable, replicateable, retrieveable, searchable, triggerable, undeletable, updateable, urls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectInfoSobjects {\n");
    sb.append("    activateable: ").append(toIndentedString(activateable)).append("\n");
    sb.append("    associateEntityType: ").append(toIndentedString(associateEntityType)).append("\n");
    sb.append("    associateParentEntity: ").append(toIndentedString(associateParentEntity)).append("\n");
    sb.append("    createable: ").append(toIndentedString(createable)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    customSetting: ").append(toIndentedString(customSetting)).append("\n");
    sb.append("    deepCloneable: ").append(toIndentedString(deepCloneable)).append("\n");
    sb.append("    deletable: ").append(toIndentedString(deletable)).append("\n");
    sb.append("    deprecatedAndHidden: ").append(toIndentedString(deprecatedAndHidden)).append("\n");
    sb.append("    feedEnabled: ").append(toIndentedString(feedEnabled)).append("\n");
    sb.append("    hasSubtypes: ").append(toIndentedString(hasSubtypes)).append("\n");
    sb.append("    isInterface: ").append(toIndentedString(isInterface)).append("\n");
    sb.append("    isSubtype: ").append(toIndentedString(isSubtype)).append("\n");
    sb.append("    keyPrefix: ").append(toIndentedString(keyPrefix)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    labelPlural: ").append(toIndentedString(labelPlural)).append("\n");
    sb.append("    layoutable: ").append(toIndentedString(layoutable)).append("\n");
    sb.append("    mergeable: ").append(toIndentedString(mergeable)).append("\n");
    sb.append("    mruEnabled: ").append(toIndentedString(mruEnabled)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    queryable: ").append(toIndentedString(queryable)).append("\n");
    sb.append("    replicateable: ").append(toIndentedString(replicateable)).append("\n");
    sb.append("    retrieveable: ").append(toIndentedString(retrieveable)).append("\n");
    sb.append("    searchable: ").append(toIndentedString(searchable)).append("\n");
    sb.append("    triggerable: ").append(toIndentedString(triggerable)).append("\n");
    sb.append("    undeletable: ").append(toIndentedString(undeletable)).append("\n");
    sb.append("    updateable: ").append(toIndentedString(updateable)).append("\n");
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

