/*
 * salesforce api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ObjectInfoUrls
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-01T18:23:34.688259300+08:00[Asia/Shanghai]")
public class ObjectInfoUrls {
  public static final String SERIALIZED_NAME_DESCRIBE = "describe";
  @SerializedName(SERIALIZED_NAME_DESCRIBE)
  private String describe;

  public static final String SERIALIZED_NAME_SOBJECT = "sobject";
  @SerializedName(SERIALIZED_NAME_SOBJECT)
  private String sobject;


  public ObjectInfoUrls describe(String describe) {
    
    this.describe = describe;
    return this;
  }

   /**
   * Get describe
   * @return describe
  **/
  @ApiModelProperty(required = true, value = "")

  public String getDescribe() {
    return describe;
  }


  public void setDescribe(String describe) {
    this.describe = describe;
  }


  public ObjectInfoUrls sobject(String sobject) {
    
    this.sobject = sobject;
    return this;
  }

   /**
   * Get sobject
   * @return sobject
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSobject() {
    return sobject;
  }


  public void setSobject(String sobject) {
    this.sobject = sobject;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectInfoUrls objectInfoUrls = (ObjectInfoUrls) o;
    return Objects.equals(this.describe, objectInfoUrls.describe) &&
        Objects.equals(this.sobject, objectInfoUrls.sobject);
  }

  @Override
  public int hashCode() {
    return Objects.hash(describe, sobject);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectInfoUrls {\n");
    sb.append("    describe: ").append(toIndentedString(describe)).append("\n");
    sb.append("    sobject: ").append(toIndentedString(sobject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

