/*
 * salesforce api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ObjectMetaDataChildRelationships
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-01T18:23:34.688259300+08:00[Asia/Shanghai]")
public class ObjectMetaDataChildRelationships {
  public static final String SERIALIZED_NAME_CASCADE_DELETE = "cascadeDelete";
  @SerializedName(SERIALIZED_NAME_CASCADE_DELETE)
  private Boolean cascadeDelete;

  public static final String SERIALIZED_NAME_CHILD_S_OBJECT = "childSObject";
  @SerializedName(SERIALIZED_NAME_CHILD_S_OBJECT)
  private String childSObject;

  public static final String SERIALIZED_NAME_DEPRECATED_AND_HIDDEN = "deprecatedAndHidden";
  @SerializedName(SERIALIZED_NAME_DEPRECATED_AND_HIDDEN)
  private Boolean deprecatedAndHidden;

  public static final String SERIALIZED_NAME_FIELD = "field";
  @SerializedName(SERIALIZED_NAME_FIELD)
  private String field;

  public static final String SERIALIZED_NAME_JUNCTION_ID_LIST_NAMES = "junctionIdListNames";
  @SerializedName(SERIALIZED_NAME_JUNCTION_ID_LIST_NAMES)
  private List<String> junctionIdListNames = new ArrayList<String>();

  public static final String SERIALIZED_NAME_JUNCTION_REFERENCE_TO = "junctionReferenceTo";
  @SerializedName(SERIALIZED_NAME_JUNCTION_REFERENCE_TO)
  private List<String> junctionReferenceTo = new ArrayList<String>();

  public static final String SERIALIZED_NAME_RELATIONSHIP_NAME = "relationshipName";
  @SerializedName(SERIALIZED_NAME_RELATIONSHIP_NAME)
  private String relationshipName;

  public static final String SERIALIZED_NAME_RESTRICTED_DELETE = "restrictedDelete";
  @SerializedName(SERIALIZED_NAME_RESTRICTED_DELETE)
  private Boolean restrictedDelete;


  public ObjectMetaDataChildRelationships cascadeDelete(Boolean cascadeDelete) {
    
    this.cascadeDelete = cascadeDelete;
    return this;
  }

   /**
   * Get cascadeDelete
   * @return cascadeDelete
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCascadeDelete() {
    return cascadeDelete;
  }


  public void setCascadeDelete(Boolean cascadeDelete) {
    this.cascadeDelete = cascadeDelete;
  }


  public ObjectMetaDataChildRelationships childSObject(String childSObject) {
    
    this.childSObject = childSObject;
    return this;
  }

   /**
   * Get childSObject
   * @return childSObject
  **/
  @ApiModelProperty(required = true, value = "")

  public String getChildSObject() {
    return childSObject;
  }


  public void setChildSObject(String childSObject) {
    this.childSObject = childSObject;
  }


  public ObjectMetaDataChildRelationships deprecatedAndHidden(Boolean deprecatedAndHidden) {
    
    this.deprecatedAndHidden = deprecatedAndHidden;
    return this;
  }

   /**
   * Get deprecatedAndHidden
   * @return deprecatedAndHidden
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDeprecatedAndHidden() {
    return deprecatedAndHidden;
  }


  public void setDeprecatedAndHidden(Boolean deprecatedAndHidden) {
    this.deprecatedAndHidden = deprecatedAndHidden;
  }


  public ObjectMetaDataChildRelationships field(String field) {
    
    this.field = field;
    return this;
  }

   /**
   * Get field
   * @return field
  **/
  @ApiModelProperty(required = true, value = "")

  public String getField() {
    return field;
  }


  public void setField(String field) {
    this.field = field;
  }


  public ObjectMetaDataChildRelationships junctionIdListNames(List<String> junctionIdListNames) {
    
    this.junctionIdListNames = junctionIdListNames;
    return this;
  }

  public ObjectMetaDataChildRelationships addJunctionIdListNamesItem(String junctionIdListNamesItem) {
    this.junctionIdListNames.add(junctionIdListNamesItem);
    return this;
  }

   /**
   * Get junctionIdListNames
   * @return junctionIdListNames
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getJunctionIdListNames() {
    return junctionIdListNames;
  }


  public void setJunctionIdListNames(List<String> junctionIdListNames) {
    this.junctionIdListNames = junctionIdListNames;
  }


  public ObjectMetaDataChildRelationships junctionReferenceTo(List<String> junctionReferenceTo) {
    
    this.junctionReferenceTo = junctionReferenceTo;
    return this;
  }

  public ObjectMetaDataChildRelationships addJunctionReferenceToItem(String junctionReferenceToItem) {
    this.junctionReferenceTo.add(junctionReferenceToItem);
    return this;
  }

   /**
   * Get junctionReferenceTo
   * @return junctionReferenceTo
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getJunctionReferenceTo() {
    return junctionReferenceTo;
  }


  public void setJunctionReferenceTo(List<String> junctionReferenceTo) {
    this.junctionReferenceTo = junctionReferenceTo;
  }


  public ObjectMetaDataChildRelationships relationshipName(String relationshipName) {
    
    this.relationshipName = relationshipName;
    return this;
  }

   /**
   * Get relationshipName
   * @return relationshipName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getRelationshipName() {
    return relationshipName;
  }


  public void setRelationshipName(String relationshipName) {
    this.relationshipName = relationshipName;
  }


  public ObjectMetaDataChildRelationships restrictedDelete(Boolean restrictedDelete) {
    
    this.restrictedDelete = restrictedDelete;
    return this;
  }

   /**
   * Get restrictedDelete
   * @return restrictedDelete
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getRestrictedDelete() {
    return restrictedDelete;
  }


  public void setRestrictedDelete(Boolean restrictedDelete) {
    this.restrictedDelete = restrictedDelete;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectMetaDataChildRelationships objectMetaDataChildRelationships = (ObjectMetaDataChildRelationships) o;
    return Objects.equals(this.cascadeDelete, objectMetaDataChildRelationships.cascadeDelete) &&
        Objects.equals(this.childSObject, objectMetaDataChildRelationships.childSObject) &&
        Objects.equals(this.deprecatedAndHidden, objectMetaDataChildRelationships.deprecatedAndHidden) &&
        Objects.equals(this.field, objectMetaDataChildRelationships.field) &&
        Objects.equals(this.junctionIdListNames, objectMetaDataChildRelationships.junctionIdListNames) &&
        Objects.equals(this.junctionReferenceTo, objectMetaDataChildRelationships.junctionReferenceTo) &&
        Objects.equals(this.relationshipName, objectMetaDataChildRelationships.relationshipName) &&
        Objects.equals(this.restrictedDelete, objectMetaDataChildRelationships.restrictedDelete);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cascadeDelete, childSObject, deprecatedAndHidden, field, junctionIdListNames, junctionReferenceTo, relationshipName, restrictedDelete);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectMetaDataChildRelationships {\n");
    sb.append("    cascadeDelete: ").append(toIndentedString(cascadeDelete)).append("\n");
    sb.append("    childSObject: ").append(toIndentedString(childSObject)).append("\n");
    sb.append("    deprecatedAndHidden: ").append(toIndentedString(deprecatedAndHidden)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    junctionIdListNames: ").append(toIndentedString(junctionIdListNames)).append("\n");
    sb.append("    junctionReferenceTo: ").append(toIndentedString(junctionReferenceTo)).append("\n");
    sb.append("    relationshipName: ").append(toIndentedString(relationshipName)).append("\n");
    sb.append("    restrictedDelete: ").append(toIndentedString(restrictedDelete)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

