/*
 * salesforce api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ObjectMetaDataActionOverrides;
import org.openapitools.client.model.ObjectMetaDataChildRelationships;
import org.openapitools.client.model.ObjectMetaDataFields;
import org.openapitools.client.model.ObjectMetaDataRecordTypeInfos;
import org.openapitools.client.model.ObjectMetaDataSupportedScopes;
import org.openapitools.client.model.ObjectMetaDataUrls1;

/**
 * ObjectMetaData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-01T18:23:34.688259300+08:00[Asia/Shanghai]")
public class ObjectMetaData {
  public static final String SERIALIZED_NAME_ACTION_OVERRIDES = "actionOverrides";
  @SerializedName(SERIALIZED_NAME_ACTION_OVERRIDES)
  private List<ObjectMetaDataActionOverrides> actionOverrides = new ArrayList<ObjectMetaDataActionOverrides>();

  public static final String SERIALIZED_NAME_ACTIVATEABLE = "activateable";
  @SerializedName(SERIALIZED_NAME_ACTIVATEABLE)
  private Boolean activateable;

  public static final String SERIALIZED_NAME_ASSOCIATE_ENTITY_TYPE = "associateEntityType";
  @SerializedName(SERIALIZED_NAME_ASSOCIATE_ENTITY_TYPE)
  private String associateEntityType;

  public static final String SERIALIZED_NAME_ASSOCIATE_PARENT_ENTITY = "associateParentEntity";
  @SerializedName(SERIALIZED_NAME_ASSOCIATE_PARENT_ENTITY)
  private String associateParentEntity;

  public static final String SERIALIZED_NAME_CHILD_RELATIONSHIPS = "childRelationships";
  @SerializedName(SERIALIZED_NAME_CHILD_RELATIONSHIPS)
  private List<ObjectMetaDataChildRelationships> childRelationships = new ArrayList<ObjectMetaDataChildRelationships>();

  public static final String SERIALIZED_NAME_COMPACT_LAYOUTABLE = "compactLayoutable";
  @SerializedName(SERIALIZED_NAME_COMPACT_LAYOUTABLE)
  private Boolean compactLayoutable;

  public static final String SERIALIZED_NAME_CREATEABLE = "createable";
  @SerializedName(SERIALIZED_NAME_CREATEABLE)
  private Boolean createable;

  public static final String SERIALIZED_NAME_CUSTOM = "custom";
  @SerializedName(SERIALIZED_NAME_CUSTOM)
  private Boolean custom;

  public static final String SERIALIZED_NAME_CUSTOM_SETTING = "customSetting";
  @SerializedName(SERIALIZED_NAME_CUSTOM_SETTING)
  private Boolean customSetting;

  public static final String SERIALIZED_NAME_DEEP_CLONEABLE = "deepCloneable";
  @SerializedName(SERIALIZED_NAME_DEEP_CLONEABLE)
  private Boolean deepCloneable;

  public static final String SERIALIZED_NAME_DEFAULT_IMPLEMENTATION = "defaultImplementation";
  @SerializedName(SERIALIZED_NAME_DEFAULT_IMPLEMENTATION)
  private String defaultImplementation;

  public static final String SERIALIZED_NAME_DELETABLE = "deletable";
  @SerializedName(SERIALIZED_NAME_DELETABLE)
  private Boolean deletable;

  public static final String SERIALIZED_NAME_DEPRECATED_AND_HIDDEN = "deprecatedAndHidden";
  @SerializedName(SERIALIZED_NAME_DEPRECATED_AND_HIDDEN)
  private Boolean deprecatedAndHidden;

  public static final String SERIALIZED_NAME_EXTENDED_BY = "extendedBy";
  @SerializedName(SERIALIZED_NAME_EXTENDED_BY)
  private String extendedBy;

  public static final String SERIALIZED_NAME_EXTENDS_INTERFACES = "extendsInterfaces";
  @SerializedName(SERIALIZED_NAME_EXTENDS_INTERFACES)
  private String extendsInterfaces;

  public static final String SERIALIZED_NAME_FEED_ENABLED = "feedEnabled";
  @SerializedName(SERIALIZED_NAME_FEED_ENABLED)
  private Boolean feedEnabled;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<ObjectMetaDataFields> fields = new ArrayList<ObjectMetaDataFields>();

  public static final String SERIALIZED_NAME_HAS_SUBTYPES = "hasSubtypes";
  @SerializedName(SERIALIZED_NAME_HAS_SUBTYPES)
  private Boolean hasSubtypes;

  public static final String SERIALIZED_NAME_IMPLEMENTED_BY = "implementedBy";
  @SerializedName(SERIALIZED_NAME_IMPLEMENTED_BY)
  private String implementedBy;

  public static final String SERIALIZED_NAME_IMPLEMENTS_INTERFACES = "implementsInterfaces";
  @SerializedName(SERIALIZED_NAME_IMPLEMENTS_INTERFACES)
  private String implementsInterfaces;

  public static final String SERIALIZED_NAME_IS_INTERFACE = "isInterface";
  @SerializedName(SERIALIZED_NAME_IS_INTERFACE)
  private Boolean isInterface;

  public static final String SERIALIZED_NAME_IS_SUBTYPE = "isSubtype";
  @SerializedName(SERIALIZED_NAME_IS_SUBTYPE)
  private Boolean isSubtype;

  public static final String SERIALIZED_NAME_KEY_PREFIX = "keyPrefix";
  @SerializedName(SERIALIZED_NAME_KEY_PREFIX)
  private String keyPrefix;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_LABEL_PLURAL = "labelPlural";
  @SerializedName(SERIALIZED_NAME_LABEL_PLURAL)
  private String labelPlural;

  public static final String SERIALIZED_NAME_LAYOUTABLE = "layoutable";
  @SerializedName(SERIALIZED_NAME_LAYOUTABLE)
  private Boolean layoutable;

  public static final String SERIALIZED_NAME_LISTVIEWABLE = "listviewable";
  @SerializedName(SERIALIZED_NAME_LISTVIEWABLE)
  private String listviewable;

  public static final String SERIALIZED_NAME_LOOKUP_LAYOUTABLE = "lookupLayoutable";
  @SerializedName(SERIALIZED_NAME_LOOKUP_LAYOUTABLE)
  private String lookupLayoutable;

  public static final String SERIALIZED_NAME_MERGEABLE = "mergeable";
  @SerializedName(SERIALIZED_NAME_MERGEABLE)
  private Boolean mergeable;

  public static final String SERIALIZED_NAME_MRU_ENABLED = "mruEnabled";
  @SerializedName(SERIALIZED_NAME_MRU_ENABLED)
  private Boolean mruEnabled;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NAMED_LAYOUT_INFOS = "namedLayoutInfos";
  @SerializedName(SERIALIZED_NAME_NAMED_LAYOUT_INFOS)
  private List<String> namedLayoutInfos = new ArrayList<String>();

  public static final String SERIALIZED_NAME_NETWORK_SCOPE_FIELD_NAME = "networkScopeFieldName";
  @SerializedName(SERIALIZED_NAME_NETWORK_SCOPE_FIELD_NAME)
  private String networkScopeFieldName;

  public static final String SERIALIZED_NAME_QUERYABLE = "queryable";
  @SerializedName(SERIALIZED_NAME_QUERYABLE)
  private Boolean queryable;

  public static final String SERIALIZED_NAME_RECORD_TYPE_INFOS = "recordTypeInfos";
  @SerializedName(SERIALIZED_NAME_RECORD_TYPE_INFOS)
  private List<ObjectMetaDataRecordTypeInfos> recordTypeInfos = new ArrayList<ObjectMetaDataRecordTypeInfos>();

  public static final String SERIALIZED_NAME_REPLICATEABLE = "replicateable";
  @SerializedName(SERIALIZED_NAME_REPLICATEABLE)
  private Boolean replicateable;

  public static final String SERIALIZED_NAME_RETRIEVEABLE = "retrieveable";
  @SerializedName(SERIALIZED_NAME_RETRIEVEABLE)
  private Boolean retrieveable;

  public static final String SERIALIZED_NAME_SEARCH_LAYOUTABLE = "searchLayoutable";
  @SerializedName(SERIALIZED_NAME_SEARCH_LAYOUTABLE)
  private Boolean searchLayoutable;

  public static final String SERIALIZED_NAME_SEARCHABLE = "searchable";
  @SerializedName(SERIALIZED_NAME_SEARCHABLE)
  private Boolean searchable;

  public static final String SERIALIZED_NAME_SOBJECT_DESCRIBE_OPTION = "sobjectDescribeOption";
  @SerializedName(SERIALIZED_NAME_SOBJECT_DESCRIBE_OPTION)
  private String sobjectDescribeOption;

  public static final String SERIALIZED_NAME_SUPPORTED_SCOPES = "supportedScopes";
  @SerializedName(SERIALIZED_NAME_SUPPORTED_SCOPES)
  private List<ObjectMetaDataSupportedScopes> supportedScopes = new ArrayList<ObjectMetaDataSupportedScopes>();

  public static final String SERIALIZED_NAME_TRIGGERABLE = "triggerable";
  @SerializedName(SERIALIZED_NAME_TRIGGERABLE)
  private Boolean triggerable;

  public static final String SERIALIZED_NAME_UNDELETABLE = "undeletable";
  @SerializedName(SERIALIZED_NAME_UNDELETABLE)
  private Boolean undeletable;

  public static final String SERIALIZED_NAME_UPDATEABLE = "updateable";
  @SerializedName(SERIALIZED_NAME_UPDATEABLE)
  private Boolean updateable;

  public static final String SERIALIZED_NAME_URLS = "urls";
  @SerializedName(SERIALIZED_NAME_URLS)
  private ObjectMetaDataUrls1 urls;


  public ObjectMetaData actionOverrides(List<ObjectMetaDataActionOverrides> actionOverrides) {
    
    this.actionOverrides = actionOverrides;
    return this;
  }

  public ObjectMetaData addActionOverridesItem(ObjectMetaDataActionOverrides actionOverridesItem) {
    this.actionOverrides.add(actionOverridesItem);
    return this;
  }

   /**
   * Get actionOverrides
   * @return actionOverrides
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ObjectMetaDataActionOverrides> getActionOverrides() {
    return actionOverrides;
  }


  public void setActionOverrides(List<ObjectMetaDataActionOverrides> actionOverrides) {
    this.actionOverrides = actionOverrides;
  }


  public ObjectMetaData activateable(Boolean activateable) {
    
    this.activateable = activateable;
    return this;
  }

   /**
   * Get activateable
   * @return activateable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getActivateable() {
    return activateable;
  }


  public void setActivateable(Boolean activateable) {
    this.activateable = activateable;
  }


  public ObjectMetaData associateEntityType(String associateEntityType) {
    
    this.associateEntityType = associateEntityType;
    return this;
  }

   /**
   * Get associateEntityType
   * @return associateEntityType
  **/
  @ApiModelProperty(required = true, value = "")

  public String getAssociateEntityType() {
    return associateEntityType;
  }


  public void setAssociateEntityType(String associateEntityType) {
    this.associateEntityType = associateEntityType;
  }


  public ObjectMetaData associateParentEntity(String associateParentEntity) {
    
    this.associateParentEntity = associateParentEntity;
    return this;
  }

   /**
   * Get associateParentEntity
   * @return associateParentEntity
  **/
  @ApiModelProperty(required = true, value = "")

  public String getAssociateParentEntity() {
    return associateParentEntity;
  }


  public void setAssociateParentEntity(String associateParentEntity) {
    this.associateParentEntity = associateParentEntity;
  }


  public ObjectMetaData childRelationships(List<ObjectMetaDataChildRelationships> childRelationships) {
    
    this.childRelationships = childRelationships;
    return this;
  }

  public ObjectMetaData addChildRelationshipsItem(ObjectMetaDataChildRelationships childRelationshipsItem) {
    this.childRelationships.add(childRelationshipsItem);
    return this;
  }

   /**
   * Get childRelationships
   * @return childRelationships
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ObjectMetaDataChildRelationships> getChildRelationships() {
    return childRelationships;
  }


  public void setChildRelationships(List<ObjectMetaDataChildRelationships> childRelationships) {
    this.childRelationships = childRelationships;
  }


  public ObjectMetaData compactLayoutable(Boolean compactLayoutable) {
    
    this.compactLayoutable = compactLayoutable;
    return this;
  }

   /**
   * Get compactLayoutable
   * @return compactLayoutable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCompactLayoutable() {
    return compactLayoutable;
  }


  public void setCompactLayoutable(Boolean compactLayoutable) {
    this.compactLayoutable = compactLayoutable;
  }


  public ObjectMetaData createable(Boolean createable) {
    
    this.createable = createable;
    return this;
  }

   /**
   * Get createable
   * @return createable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCreateable() {
    return createable;
  }


  public void setCreateable(Boolean createable) {
    this.createable = createable;
  }


  public ObjectMetaData custom(Boolean custom) {
    
    this.custom = custom;
    return this;
  }

   /**
   * Get custom
   * @return custom
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCustom() {
    return custom;
  }


  public void setCustom(Boolean custom) {
    this.custom = custom;
  }


  public ObjectMetaData customSetting(Boolean customSetting) {
    
    this.customSetting = customSetting;
    return this;
  }

   /**
   * Get customSetting
   * @return customSetting
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCustomSetting() {
    return customSetting;
  }


  public void setCustomSetting(Boolean customSetting) {
    this.customSetting = customSetting;
  }


  public ObjectMetaData deepCloneable(Boolean deepCloneable) {
    
    this.deepCloneable = deepCloneable;
    return this;
  }

   /**
   * Get deepCloneable
   * @return deepCloneable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDeepCloneable() {
    return deepCloneable;
  }


  public void setDeepCloneable(Boolean deepCloneable) {
    this.deepCloneable = deepCloneable;
  }


  public ObjectMetaData defaultImplementation(String defaultImplementation) {
    
    this.defaultImplementation = defaultImplementation;
    return this;
  }

   /**
   * Get defaultImplementation
   * @return defaultImplementation
  **/
  @ApiModelProperty(required = true, value = "")

  public String getDefaultImplementation() {
    return defaultImplementation;
  }


  public void setDefaultImplementation(String defaultImplementation) {
    this.defaultImplementation = defaultImplementation;
  }


  public ObjectMetaData deletable(Boolean deletable) {
    
    this.deletable = deletable;
    return this;
  }

   /**
   * Get deletable
   * @return deletable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDeletable() {
    return deletable;
  }


  public void setDeletable(Boolean deletable) {
    this.deletable = deletable;
  }


  public ObjectMetaData deprecatedAndHidden(Boolean deprecatedAndHidden) {
    
    this.deprecatedAndHidden = deprecatedAndHidden;
    return this;
  }

   /**
   * Get deprecatedAndHidden
   * @return deprecatedAndHidden
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDeprecatedAndHidden() {
    return deprecatedAndHidden;
  }


  public void setDeprecatedAndHidden(Boolean deprecatedAndHidden) {
    this.deprecatedAndHidden = deprecatedAndHidden;
  }


  public ObjectMetaData extendedBy(String extendedBy) {
    
    this.extendedBy = extendedBy;
    return this;
  }

   /**
   * Get extendedBy
   * @return extendedBy
  **/
  @ApiModelProperty(required = true, value = "")

  public String getExtendedBy() {
    return extendedBy;
  }


  public void setExtendedBy(String extendedBy) {
    this.extendedBy = extendedBy;
  }


  public ObjectMetaData extendsInterfaces(String extendsInterfaces) {
    
    this.extendsInterfaces = extendsInterfaces;
    return this;
  }

   /**
   * Get extendsInterfaces
   * @return extendsInterfaces
  **/
  @ApiModelProperty(required = true, value = "")

  public String getExtendsInterfaces() {
    return extendsInterfaces;
  }


  public void setExtendsInterfaces(String extendsInterfaces) {
    this.extendsInterfaces = extendsInterfaces;
  }


  public ObjectMetaData feedEnabled(Boolean feedEnabled) {
    
    this.feedEnabled = feedEnabled;
    return this;
  }

   /**
   * Get feedEnabled
   * @return feedEnabled
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getFeedEnabled() {
    return feedEnabled;
  }


  public void setFeedEnabled(Boolean feedEnabled) {
    this.feedEnabled = feedEnabled;
  }


  public ObjectMetaData fields(List<ObjectMetaDataFields> fields) {
    
    this.fields = fields;
    return this;
  }

  public ObjectMetaData addFieldsItem(ObjectMetaDataFields fieldsItem) {
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ObjectMetaDataFields> getFields() {
    return fields;
  }


  public void setFields(List<ObjectMetaDataFields> fields) {
    this.fields = fields;
  }


  public ObjectMetaData hasSubtypes(Boolean hasSubtypes) {
    
    this.hasSubtypes = hasSubtypes;
    return this;
  }

   /**
   * Get hasSubtypes
   * @return hasSubtypes
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getHasSubtypes() {
    return hasSubtypes;
  }


  public void setHasSubtypes(Boolean hasSubtypes) {
    this.hasSubtypes = hasSubtypes;
  }


  public ObjectMetaData implementedBy(String implementedBy) {
    
    this.implementedBy = implementedBy;
    return this;
  }

   /**
   * Get implementedBy
   * @return implementedBy
  **/
  @ApiModelProperty(required = true, value = "")

  public String getImplementedBy() {
    return implementedBy;
  }


  public void setImplementedBy(String implementedBy) {
    this.implementedBy = implementedBy;
  }


  public ObjectMetaData implementsInterfaces(String implementsInterfaces) {
    
    this.implementsInterfaces = implementsInterfaces;
    return this;
  }

   /**
   * Get implementsInterfaces
   * @return implementsInterfaces
  **/
  @ApiModelProperty(required = true, value = "")

  public String getImplementsInterfaces() {
    return implementsInterfaces;
  }


  public void setImplementsInterfaces(String implementsInterfaces) {
    this.implementsInterfaces = implementsInterfaces;
  }


  public ObjectMetaData isInterface(Boolean isInterface) {
    
    this.isInterface = isInterface;
    return this;
  }

   /**
   * Get isInterface
   * @return isInterface
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getIsInterface() {
    return isInterface;
  }


  public void setIsInterface(Boolean isInterface) {
    this.isInterface = isInterface;
  }


  public ObjectMetaData isSubtype(Boolean isSubtype) {
    
    this.isSubtype = isSubtype;
    return this;
  }

   /**
   * Get isSubtype
   * @return isSubtype
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getIsSubtype() {
    return isSubtype;
  }


  public void setIsSubtype(Boolean isSubtype) {
    this.isSubtype = isSubtype;
  }


  public ObjectMetaData keyPrefix(String keyPrefix) {
    
    this.keyPrefix = keyPrefix;
    return this;
  }

   /**
   * Get keyPrefix
   * @return keyPrefix
  **/
  @ApiModelProperty(required = true, value = "")

  public String getKeyPrefix() {
    return keyPrefix;
  }


  public void setKeyPrefix(String keyPrefix) {
    this.keyPrefix = keyPrefix;
  }


  public ObjectMetaData label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public ObjectMetaData labelPlural(String labelPlural) {
    
    this.labelPlural = labelPlural;
    return this;
  }

   /**
   * Get labelPlural
   * @return labelPlural
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLabelPlural() {
    return labelPlural;
  }


  public void setLabelPlural(String labelPlural) {
    this.labelPlural = labelPlural;
  }


  public ObjectMetaData layoutable(Boolean layoutable) {
    
    this.layoutable = layoutable;
    return this;
  }

   /**
   * Get layoutable
   * @return layoutable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getLayoutable() {
    return layoutable;
  }


  public void setLayoutable(Boolean layoutable) {
    this.layoutable = layoutable;
  }


  public ObjectMetaData listviewable(String listviewable) {
    
    this.listviewable = listviewable;
    return this;
  }

   /**
   * Get listviewable
   * @return listviewable
  **/
  @ApiModelProperty(required = true, value = "")

  public String getListviewable() {
    return listviewable;
  }


  public void setListviewable(String listviewable) {
    this.listviewable = listviewable;
  }


  public ObjectMetaData lookupLayoutable(String lookupLayoutable) {
    
    this.lookupLayoutable = lookupLayoutable;
    return this;
  }

   /**
   * Get lookupLayoutable
   * @return lookupLayoutable
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLookupLayoutable() {
    return lookupLayoutable;
  }


  public void setLookupLayoutable(String lookupLayoutable) {
    this.lookupLayoutable = lookupLayoutable;
  }


  public ObjectMetaData mergeable(Boolean mergeable) {
    
    this.mergeable = mergeable;
    return this;
  }

   /**
   * Get mergeable
   * @return mergeable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getMergeable() {
    return mergeable;
  }


  public void setMergeable(Boolean mergeable) {
    this.mergeable = mergeable;
  }


  public ObjectMetaData mruEnabled(Boolean mruEnabled) {
    
    this.mruEnabled = mruEnabled;
    return this;
  }

   /**
   * Get mruEnabled
   * @return mruEnabled
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getMruEnabled() {
    return mruEnabled;
  }


  public void setMruEnabled(Boolean mruEnabled) {
    this.mruEnabled = mruEnabled;
  }


  public ObjectMetaData name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ObjectMetaData namedLayoutInfos(List<String> namedLayoutInfos) {
    
    this.namedLayoutInfos = namedLayoutInfos;
    return this;
  }

  public ObjectMetaData addNamedLayoutInfosItem(String namedLayoutInfosItem) {
    this.namedLayoutInfos.add(namedLayoutInfosItem);
    return this;
  }

   /**
   * Get namedLayoutInfos
   * @return namedLayoutInfos
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getNamedLayoutInfos() {
    return namedLayoutInfos;
  }


  public void setNamedLayoutInfos(List<String> namedLayoutInfos) {
    this.namedLayoutInfos = namedLayoutInfos;
  }


  public ObjectMetaData networkScopeFieldName(String networkScopeFieldName) {
    
    this.networkScopeFieldName = networkScopeFieldName;
    return this;
  }

   /**
   * Get networkScopeFieldName
   * @return networkScopeFieldName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getNetworkScopeFieldName() {
    return networkScopeFieldName;
  }


  public void setNetworkScopeFieldName(String networkScopeFieldName) {
    this.networkScopeFieldName = networkScopeFieldName;
  }


  public ObjectMetaData queryable(Boolean queryable) {
    
    this.queryable = queryable;
    return this;
  }

   /**
   * Get queryable
   * @return queryable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getQueryable() {
    return queryable;
  }


  public void setQueryable(Boolean queryable) {
    this.queryable = queryable;
  }


  public ObjectMetaData recordTypeInfos(List<ObjectMetaDataRecordTypeInfos> recordTypeInfos) {
    
    this.recordTypeInfos = recordTypeInfos;
    return this;
  }

  public ObjectMetaData addRecordTypeInfosItem(ObjectMetaDataRecordTypeInfos recordTypeInfosItem) {
    this.recordTypeInfos.add(recordTypeInfosItem);
    return this;
  }

   /**
   * Get recordTypeInfos
   * @return recordTypeInfos
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ObjectMetaDataRecordTypeInfos> getRecordTypeInfos() {
    return recordTypeInfos;
  }


  public void setRecordTypeInfos(List<ObjectMetaDataRecordTypeInfos> recordTypeInfos) {
    this.recordTypeInfos = recordTypeInfos;
  }


  public ObjectMetaData replicateable(Boolean replicateable) {
    
    this.replicateable = replicateable;
    return this;
  }

   /**
   * Get replicateable
   * @return replicateable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getReplicateable() {
    return replicateable;
  }


  public void setReplicateable(Boolean replicateable) {
    this.replicateable = replicateable;
  }


  public ObjectMetaData retrieveable(Boolean retrieveable) {
    
    this.retrieveable = retrieveable;
    return this;
  }

   /**
   * Get retrieveable
   * @return retrieveable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getRetrieveable() {
    return retrieveable;
  }


  public void setRetrieveable(Boolean retrieveable) {
    this.retrieveable = retrieveable;
  }


  public ObjectMetaData searchLayoutable(Boolean searchLayoutable) {
    
    this.searchLayoutable = searchLayoutable;
    return this;
  }

   /**
   * Get searchLayoutable
   * @return searchLayoutable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getSearchLayoutable() {
    return searchLayoutable;
  }


  public void setSearchLayoutable(Boolean searchLayoutable) {
    this.searchLayoutable = searchLayoutable;
  }


  public ObjectMetaData searchable(Boolean searchable) {
    
    this.searchable = searchable;
    return this;
  }

   /**
   * Get searchable
   * @return searchable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getSearchable() {
    return searchable;
  }


  public void setSearchable(Boolean searchable) {
    this.searchable = searchable;
  }


  public ObjectMetaData sobjectDescribeOption(String sobjectDescribeOption) {
    
    this.sobjectDescribeOption = sobjectDescribeOption;
    return this;
  }

   /**
   * Get sobjectDescribeOption
   * @return sobjectDescribeOption
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSobjectDescribeOption() {
    return sobjectDescribeOption;
  }


  public void setSobjectDescribeOption(String sobjectDescribeOption) {
    this.sobjectDescribeOption = sobjectDescribeOption;
  }


  public ObjectMetaData supportedScopes(List<ObjectMetaDataSupportedScopes> supportedScopes) {
    
    this.supportedScopes = supportedScopes;
    return this;
  }

  public ObjectMetaData addSupportedScopesItem(ObjectMetaDataSupportedScopes supportedScopesItem) {
    this.supportedScopes.add(supportedScopesItem);
    return this;
  }

   /**
   * Get supportedScopes
   * @return supportedScopes
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ObjectMetaDataSupportedScopes> getSupportedScopes() {
    return supportedScopes;
  }


  public void setSupportedScopes(List<ObjectMetaDataSupportedScopes> supportedScopes) {
    this.supportedScopes = supportedScopes;
  }


  public ObjectMetaData triggerable(Boolean triggerable) {
    
    this.triggerable = triggerable;
    return this;
  }

   /**
   * Get triggerable
   * @return triggerable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getTriggerable() {
    return triggerable;
  }


  public void setTriggerable(Boolean triggerable) {
    this.triggerable = triggerable;
  }


  public ObjectMetaData undeletable(Boolean undeletable) {
    
    this.undeletable = undeletable;
    return this;
  }

   /**
   * Get undeletable
   * @return undeletable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getUndeletable() {
    return undeletable;
  }


  public void setUndeletable(Boolean undeletable) {
    this.undeletable = undeletable;
  }


  public ObjectMetaData updateable(Boolean updateable) {
    
    this.updateable = updateable;
    return this;
  }

   /**
   * Get updateable
   * @return updateable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getUpdateable() {
    return updateable;
  }


  public void setUpdateable(Boolean updateable) {
    this.updateable = updateable;
  }


  public ObjectMetaData urls(ObjectMetaDataUrls1 urls) {
    
    this.urls = urls;
    return this;
  }

   /**
   * Get urls
   * @return urls
  **/
  @ApiModelProperty(required = true, value = "")

  public ObjectMetaDataUrls1 getUrls() {
    return urls;
  }


  public void setUrls(ObjectMetaDataUrls1 urls) {
    this.urls = urls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectMetaData objectMetaData = (ObjectMetaData) o;
    return Objects.equals(this.actionOverrides, objectMetaData.actionOverrides) &&
        Objects.equals(this.activateable, objectMetaData.activateable) &&
        Objects.equals(this.associateEntityType, objectMetaData.associateEntityType) &&
        Objects.equals(this.associateParentEntity, objectMetaData.associateParentEntity) &&
        Objects.equals(this.childRelationships, objectMetaData.childRelationships) &&
        Objects.equals(this.compactLayoutable, objectMetaData.compactLayoutable) &&
        Objects.equals(this.createable, objectMetaData.createable) &&
        Objects.equals(this.custom, objectMetaData.custom) &&
        Objects.equals(this.customSetting, objectMetaData.customSetting) &&
        Objects.equals(this.deepCloneable, objectMetaData.deepCloneable) &&
        Objects.equals(this.defaultImplementation, objectMetaData.defaultImplementation) &&
        Objects.equals(this.deletable, objectMetaData.deletable) &&
        Objects.equals(this.deprecatedAndHidden, objectMetaData.deprecatedAndHidden) &&
        Objects.equals(this.extendedBy, objectMetaData.extendedBy) &&
        Objects.equals(this.extendsInterfaces, objectMetaData.extendsInterfaces) &&
        Objects.equals(this.feedEnabled, objectMetaData.feedEnabled) &&
        Objects.equals(this.fields, objectMetaData.fields) &&
        Objects.equals(this.hasSubtypes, objectMetaData.hasSubtypes) &&
        Objects.equals(this.implementedBy, objectMetaData.implementedBy) &&
        Objects.equals(this.implementsInterfaces, objectMetaData.implementsInterfaces) &&
        Objects.equals(this.isInterface, objectMetaData.isInterface) &&
        Objects.equals(this.isSubtype, objectMetaData.isSubtype) &&
        Objects.equals(this.keyPrefix, objectMetaData.keyPrefix) &&
        Objects.equals(this.label, objectMetaData.label) &&
        Objects.equals(this.labelPlural, objectMetaData.labelPlural) &&
        Objects.equals(this.layoutable, objectMetaData.layoutable) &&
        Objects.equals(this.listviewable, objectMetaData.listviewable) &&
        Objects.equals(this.lookupLayoutable, objectMetaData.lookupLayoutable) &&
        Objects.equals(this.mergeable, objectMetaData.mergeable) &&
        Objects.equals(this.mruEnabled, objectMetaData.mruEnabled) &&
        Objects.equals(this.name, objectMetaData.name) &&
        Objects.equals(this.namedLayoutInfos, objectMetaData.namedLayoutInfos) &&
        Objects.equals(this.networkScopeFieldName, objectMetaData.networkScopeFieldName) &&
        Objects.equals(this.queryable, objectMetaData.queryable) &&
        Objects.equals(this.recordTypeInfos, objectMetaData.recordTypeInfos) &&
        Objects.equals(this.replicateable, objectMetaData.replicateable) &&
        Objects.equals(this.retrieveable, objectMetaData.retrieveable) &&
        Objects.equals(this.searchLayoutable, objectMetaData.searchLayoutable) &&
        Objects.equals(this.searchable, objectMetaData.searchable) &&
        Objects.equals(this.sobjectDescribeOption, objectMetaData.sobjectDescribeOption) &&
        Objects.equals(this.supportedScopes, objectMetaData.supportedScopes) &&
        Objects.equals(this.triggerable, objectMetaData.triggerable) &&
        Objects.equals(this.undeletable, objectMetaData.undeletable) &&
        Objects.equals(this.updateable, objectMetaData.updateable) &&
        Objects.equals(this.urls, objectMetaData.urls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionOverrides, activateable, associateEntityType, associateParentEntity, childRelationships, compactLayoutable, createable, custom, customSetting, deepCloneable, defaultImplementation, deletable, deprecatedAndHidden, extendedBy, extendsInterfaces, feedEnabled, fields, hasSubtypes, implementedBy, implementsInterfaces, isInterface, isSubtype, keyPrefix, label, labelPlural, layoutable, listviewable, lookupLayoutable, mergeable, mruEnabled, name, namedLayoutInfos, networkScopeFieldName, queryable, recordTypeInfos, replicateable, retrieveable, searchLayoutable, searchable, sobjectDescribeOption, supportedScopes, triggerable, undeletable, updateable, urls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectMetaData {\n");
    sb.append("    actionOverrides: ").append(toIndentedString(actionOverrides)).append("\n");
    sb.append("    activateable: ").append(toIndentedString(activateable)).append("\n");
    sb.append("    associateEntityType: ").append(toIndentedString(associateEntityType)).append("\n");
    sb.append("    associateParentEntity: ").append(toIndentedString(associateParentEntity)).append("\n");
    sb.append("    childRelationships: ").append(toIndentedString(childRelationships)).append("\n");
    sb.append("    compactLayoutable: ").append(toIndentedString(compactLayoutable)).append("\n");
    sb.append("    createable: ").append(toIndentedString(createable)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    customSetting: ").append(toIndentedString(customSetting)).append("\n");
    sb.append("    deepCloneable: ").append(toIndentedString(deepCloneable)).append("\n");
    sb.append("    defaultImplementation: ").append(toIndentedString(defaultImplementation)).append("\n");
    sb.append("    deletable: ").append(toIndentedString(deletable)).append("\n");
    sb.append("    deprecatedAndHidden: ").append(toIndentedString(deprecatedAndHidden)).append("\n");
    sb.append("    extendedBy: ").append(toIndentedString(extendedBy)).append("\n");
    sb.append("    extendsInterfaces: ").append(toIndentedString(extendsInterfaces)).append("\n");
    sb.append("    feedEnabled: ").append(toIndentedString(feedEnabled)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    hasSubtypes: ").append(toIndentedString(hasSubtypes)).append("\n");
    sb.append("    implementedBy: ").append(toIndentedString(implementedBy)).append("\n");
    sb.append("    implementsInterfaces: ").append(toIndentedString(implementsInterfaces)).append("\n");
    sb.append("    isInterface: ").append(toIndentedString(isInterface)).append("\n");
    sb.append("    isSubtype: ").append(toIndentedString(isSubtype)).append("\n");
    sb.append("    keyPrefix: ").append(toIndentedString(keyPrefix)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    labelPlural: ").append(toIndentedString(labelPlural)).append("\n");
    sb.append("    layoutable: ").append(toIndentedString(layoutable)).append("\n");
    sb.append("    listviewable: ").append(toIndentedString(listviewable)).append("\n");
    sb.append("    lookupLayoutable: ").append(toIndentedString(lookupLayoutable)).append("\n");
    sb.append("    mergeable: ").append(toIndentedString(mergeable)).append("\n");
    sb.append("    mruEnabled: ").append(toIndentedString(mruEnabled)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namedLayoutInfos: ").append(toIndentedString(namedLayoutInfos)).append("\n");
    sb.append("    networkScopeFieldName: ").append(toIndentedString(networkScopeFieldName)).append("\n");
    sb.append("    queryable: ").append(toIndentedString(queryable)).append("\n");
    sb.append("    recordTypeInfos: ").append(toIndentedString(recordTypeInfos)).append("\n");
    sb.append("    replicateable: ").append(toIndentedString(replicateable)).append("\n");
    sb.append("    retrieveable: ").append(toIndentedString(retrieveable)).append("\n");
    sb.append("    searchLayoutable: ").append(toIndentedString(searchLayoutable)).append("\n");
    sb.append("    searchable: ").append(toIndentedString(searchable)).append("\n");
    sb.append("    sobjectDescribeOption: ").append(toIndentedString(sobjectDescribeOption)).append("\n");
    sb.append("    supportedScopes: ").append(toIndentedString(supportedScopes)).append("\n");
    sb.append("    triggerable: ").append(toIndentedString(triggerable)).append("\n");
    sb.append("    undeletable: ").append(toIndentedString(undeletable)).append("\n");
    sb.append("    updateable: ").append(toIndentedString(updateable)).append("\n");
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

