/*
 * salesforce api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ObjectMetaDataPicklistValues;

/**
 * ObjectMetaDataFields
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-01T18:23:34.688259300+08:00[Asia/Shanghai]")
public class ObjectMetaDataFields {
  public static final String SERIALIZED_NAME_AGGREGATABLE = "aggregatable";
  @SerializedName(SERIALIZED_NAME_AGGREGATABLE)
  private Boolean aggregatable;

  public static final String SERIALIZED_NAME_AI_PREDICTION_FIELD = "aiPredictionField";
  @SerializedName(SERIALIZED_NAME_AI_PREDICTION_FIELD)
  private Boolean aiPredictionField;

  public static final String SERIALIZED_NAME_AUTO_NUMBER = "autoNumber";
  @SerializedName(SERIALIZED_NAME_AUTO_NUMBER)
  private Boolean autoNumber;

  public static final String SERIALIZED_NAME_BYTE_LENGTH = "byteLength";
  @SerializedName(SERIALIZED_NAME_BYTE_LENGTH)
  private Integer byteLength;

  public static final String SERIALIZED_NAME_CALCULATED = "calculated";
  @SerializedName(SERIALIZED_NAME_CALCULATED)
  private Boolean calculated;

  public static final String SERIALIZED_NAME_CALCULATED_FORMULA = "calculatedFormula";
  @SerializedName(SERIALIZED_NAME_CALCULATED_FORMULA)
  private String calculatedFormula;

  public static final String SERIALIZED_NAME_CASCADE_DELETE = "cascadeDelete";
  @SerializedName(SERIALIZED_NAME_CASCADE_DELETE)
  private Boolean cascadeDelete;

  public static final String SERIALIZED_NAME_CASE_SENSITIVE = "caseSensitive";
  @SerializedName(SERIALIZED_NAME_CASE_SENSITIVE)
  private Boolean caseSensitive;

  public static final String SERIALIZED_NAME_COMPOUND_FIELD_NAME = "compoundFieldName";
  @SerializedName(SERIALIZED_NAME_COMPOUND_FIELD_NAME)
  private String compoundFieldName;

  public static final String SERIALIZED_NAME_CONTROLLER_NAME = "controllerName";
  @SerializedName(SERIALIZED_NAME_CONTROLLER_NAME)
  private String controllerName;

  public static final String SERIALIZED_NAME_CREATEABLE = "createable";
  @SerializedName(SERIALIZED_NAME_CREATEABLE)
  private Boolean createable;

  public static final String SERIALIZED_NAME_CUSTOM = "custom";
  @SerializedName(SERIALIZED_NAME_CUSTOM)
  private Boolean custom;

  public static final String SERIALIZED_NAME_DEFAULT_VALUE = "defaultValue";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE)
  private String defaultValue;

  public static final String SERIALIZED_NAME_DEFAULT_VALUE_FORMULA = "defaultValueFormula";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE_FORMULA)
  private String defaultValueFormula;

  public static final String SERIALIZED_NAME_DEFAULTED_ON_CREATE = "defaultedOnCreate";
  @SerializedName(SERIALIZED_NAME_DEFAULTED_ON_CREATE)
  private Boolean defaultedOnCreate;

  public static final String SERIALIZED_NAME_DEPENDENT_PICKLIST = "dependentPicklist";
  @SerializedName(SERIALIZED_NAME_DEPENDENT_PICKLIST)
  private Boolean dependentPicklist;

  public static final String SERIALIZED_NAME_DEPRECATED_AND_HIDDEN = "deprecatedAndHidden";
  @SerializedName(SERIALIZED_NAME_DEPRECATED_AND_HIDDEN)
  private Boolean deprecatedAndHidden;

  public static final String SERIALIZED_NAME_DIGITS = "digits";
  @SerializedName(SERIALIZED_NAME_DIGITS)
  private Integer digits;

  public static final String SERIALIZED_NAME_DISPLAY_LOCATION_IN_DECIMAL = "displayLocationInDecimal";
  @SerializedName(SERIALIZED_NAME_DISPLAY_LOCATION_IN_DECIMAL)
  private Boolean displayLocationInDecimal;

  public static final String SERIALIZED_NAME_ENCRYPTED = "encrypted";
  @SerializedName(SERIALIZED_NAME_ENCRYPTED)
  private Boolean encrypted;

  public static final String SERIALIZED_NAME_EXTERNAL_ID = "externalId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ID)
  private Boolean externalId;

  public static final String SERIALIZED_NAME_EXTRA_TYPE_INFO = "extraTypeInfo";
  @SerializedName(SERIALIZED_NAME_EXTRA_TYPE_INFO)
  private String extraTypeInfo;

  public static final String SERIALIZED_NAME_FILTERABLE = "filterable";
  @SerializedName(SERIALIZED_NAME_FILTERABLE)
  private Boolean filterable;

  public static final String SERIALIZED_NAME_FILTERED_LOOKUP_INFO = "filteredLookupInfo";
  @SerializedName(SERIALIZED_NAME_FILTERED_LOOKUP_INFO)
  private String filteredLookupInfo;

  public static final String SERIALIZED_NAME_FORMULA_TREAT_NULL_NUMBER_AS_ZERO = "formulaTreatNullNumberAsZero";
  @SerializedName(SERIALIZED_NAME_FORMULA_TREAT_NULL_NUMBER_AS_ZERO)
  private Boolean formulaTreatNullNumberAsZero;

  public static final String SERIALIZED_NAME_GROUPABLE = "groupable";
  @SerializedName(SERIALIZED_NAME_GROUPABLE)
  private Boolean groupable;

  public static final String SERIALIZED_NAME_HIGH_SCALE_NUMBER = "highScaleNumber";
  @SerializedName(SERIALIZED_NAME_HIGH_SCALE_NUMBER)
  private Boolean highScaleNumber;

  public static final String SERIALIZED_NAME_HTML_FORMATTED = "htmlFormatted";
  @SerializedName(SERIALIZED_NAME_HTML_FORMATTED)
  private Boolean htmlFormatted;

  public static final String SERIALIZED_NAME_ID_LOOKUP = "idLookup";
  @SerializedName(SERIALIZED_NAME_ID_LOOKUP)
  private Boolean idLookup;

  public static final String SERIALIZED_NAME_INLINE_HELP_TEXT = "inlineHelpText";
  @SerializedName(SERIALIZED_NAME_INLINE_HELP_TEXT)
  private String inlineHelpText;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_LENGTH = "length";
  @SerializedName(SERIALIZED_NAME_LENGTH)
  private Integer length;

  public static final String SERIALIZED_NAME_MASK = "mask";
  @SerializedName(SERIALIZED_NAME_MASK)
  private String mask;

  public static final String SERIALIZED_NAME_MASK_TYPE = "maskType";
  @SerializedName(SERIALIZED_NAME_MASK_TYPE)
  private String maskType;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NAME_FIELD = "nameField";
  @SerializedName(SERIALIZED_NAME_NAME_FIELD)
  private Boolean nameField;

  public static final String SERIALIZED_NAME_NAME_POINTING = "namePointing";
  @SerializedName(SERIALIZED_NAME_NAME_POINTING)
  private Boolean namePointing;

  public static final String SERIALIZED_NAME_NILLABLE = "nillable";
  @SerializedName(SERIALIZED_NAME_NILLABLE)
  private Boolean nillable;

  public static final String SERIALIZED_NAME_PERMISSIONABLE = "permissionable";
  @SerializedName(SERIALIZED_NAME_PERMISSIONABLE)
  private Boolean permissionable;

  public static final String SERIALIZED_NAME_PICKLIST_VALUES = "picklistValues";
  @SerializedName(SERIALIZED_NAME_PICKLIST_VALUES)
  private List<ObjectMetaDataPicklistValues> picklistValues = new ArrayList<ObjectMetaDataPicklistValues>();

  public static final String SERIALIZED_NAME_POLYMORPHIC_FOREIGN_KEY = "polymorphicForeignKey";
  @SerializedName(SERIALIZED_NAME_POLYMORPHIC_FOREIGN_KEY)
  private Boolean polymorphicForeignKey;

  public static final String SERIALIZED_NAME_PRECISION = "precision";
  @SerializedName(SERIALIZED_NAME_PRECISION)
  private Integer precision;

  public static final String SERIALIZED_NAME_QUERY_BY_DISTANCE = "queryByDistance";
  @SerializedName(SERIALIZED_NAME_QUERY_BY_DISTANCE)
  private Boolean queryByDistance;

  public static final String SERIALIZED_NAME_REFERENCE_TARGET_FIELD = "referenceTargetField";
  @SerializedName(SERIALIZED_NAME_REFERENCE_TARGET_FIELD)
  private String referenceTargetField;

  public static final String SERIALIZED_NAME_REFERENCE_TO = "referenceTo";
  @SerializedName(SERIALIZED_NAME_REFERENCE_TO)
  private List<String> referenceTo = new ArrayList<String>();

  public static final String SERIALIZED_NAME_RELATIONSHIP_NAME = "relationshipName";
  @SerializedName(SERIALIZED_NAME_RELATIONSHIP_NAME)
  private String relationshipName;

  public static final String SERIALIZED_NAME_RELATIONSHIP_ORDER = "relationshipOrder";
  @SerializedName(SERIALIZED_NAME_RELATIONSHIP_ORDER)
  private String relationshipOrder;

  public static final String SERIALIZED_NAME_RESTRICTED_DELETE = "restrictedDelete";
  @SerializedName(SERIALIZED_NAME_RESTRICTED_DELETE)
  private Boolean restrictedDelete;

  public static final String SERIALIZED_NAME_RESTRICTED_PICKLIST = "restrictedPicklist";
  @SerializedName(SERIALIZED_NAME_RESTRICTED_PICKLIST)
  private Boolean restrictedPicklist;

  public static final String SERIALIZED_NAME_SCALE = "scale";
  @SerializedName(SERIALIZED_NAME_SCALE)
  private Integer scale;

  public static final String SERIALIZED_NAME_SEARCH_PREFILTERABLE = "searchPrefilterable";
  @SerializedName(SERIALIZED_NAME_SEARCH_PREFILTERABLE)
  private Boolean searchPrefilterable;

  public static final String SERIALIZED_NAME_SOAP_TYPE = "soapType";
  @SerializedName(SERIALIZED_NAME_SOAP_TYPE)
  private String soapType;

  public static final String SERIALIZED_NAME_SORTABLE = "sortable";
  @SerializedName(SERIALIZED_NAME_SORTABLE)
  private Boolean sortable;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_UNIQUE = "unique";
  @SerializedName(SERIALIZED_NAME_UNIQUE)
  private Boolean unique;

  public static final String SERIALIZED_NAME_UPDATEABLE = "updateable";
  @SerializedName(SERIALIZED_NAME_UPDATEABLE)
  private Boolean updateable;

  public static final String SERIALIZED_NAME_WRITE_REQUIRES_MASTER_READ = "writeRequiresMasterRead";
  @SerializedName(SERIALIZED_NAME_WRITE_REQUIRES_MASTER_READ)
  private Boolean writeRequiresMasterRead;


  public ObjectMetaDataFields aggregatable(Boolean aggregatable) {
    
    this.aggregatable = aggregatable;
    return this;
  }

   /**
   * Get aggregatable
   * @return aggregatable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getAggregatable() {
    return aggregatable;
  }


  public void setAggregatable(Boolean aggregatable) {
    this.aggregatable = aggregatable;
  }


  public ObjectMetaDataFields aiPredictionField(Boolean aiPredictionField) {
    
    this.aiPredictionField = aiPredictionField;
    return this;
  }

   /**
   * Get aiPredictionField
   * @return aiPredictionField
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getAiPredictionField() {
    return aiPredictionField;
  }


  public void setAiPredictionField(Boolean aiPredictionField) {
    this.aiPredictionField = aiPredictionField;
  }


  public ObjectMetaDataFields autoNumber(Boolean autoNumber) {
    
    this.autoNumber = autoNumber;
    return this;
  }

   /**
   * Get autoNumber
   * @return autoNumber
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getAutoNumber() {
    return autoNumber;
  }


  public void setAutoNumber(Boolean autoNumber) {
    this.autoNumber = autoNumber;
  }


  public ObjectMetaDataFields byteLength(Integer byteLength) {
    
    this.byteLength = byteLength;
    return this;
  }

   /**
   * Get byteLength
   * @return byteLength
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getByteLength() {
    return byteLength;
  }


  public void setByteLength(Integer byteLength) {
    this.byteLength = byteLength;
  }


  public ObjectMetaDataFields calculated(Boolean calculated) {
    
    this.calculated = calculated;
    return this;
  }

   /**
   * Get calculated
   * @return calculated
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCalculated() {
    return calculated;
  }


  public void setCalculated(Boolean calculated) {
    this.calculated = calculated;
  }


  public ObjectMetaDataFields calculatedFormula(String calculatedFormula) {
    
    this.calculatedFormula = calculatedFormula;
    return this;
  }

   /**
   * Get calculatedFormula
   * @return calculatedFormula
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getCalculatedFormula() {
    return calculatedFormula;
  }


  public void setCalculatedFormula(String calculatedFormula) {
    this.calculatedFormula = calculatedFormula;
  }


  public ObjectMetaDataFields cascadeDelete(Boolean cascadeDelete) {
    
    this.cascadeDelete = cascadeDelete;
    return this;
  }

   /**
   * Get cascadeDelete
   * @return cascadeDelete
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCascadeDelete() {
    return cascadeDelete;
  }


  public void setCascadeDelete(Boolean cascadeDelete) {
    this.cascadeDelete = cascadeDelete;
  }


  public ObjectMetaDataFields caseSensitive(Boolean caseSensitive) {
    
    this.caseSensitive = caseSensitive;
    return this;
  }

   /**
   * Get caseSensitive
   * @return caseSensitive
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCaseSensitive() {
    return caseSensitive;
  }


  public void setCaseSensitive(Boolean caseSensitive) {
    this.caseSensitive = caseSensitive;
  }


  public ObjectMetaDataFields compoundFieldName(String compoundFieldName) {
    
    this.compoundFieldName = compoundFieldName;
    return this;
  }

   /**
   * Get compoundFieldName
   * @return compoundFieldName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getCompoundFieldName() {
    return compoundFieldName;
  }


  public void setCompoundFieldName(String compoundFieldName) {
    this.compoundFieldName = compoundFieldName;
  }


  public ObjectMetaDataFields controllerName(String controllerName) {
    
    this.controllerName = controllerName;
    return this;
  }

   /**
   * Get controllerName
   * @return controllerName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getControllerName() {
    return controllerName;
  }


  public void setControllerName(String controllerName) {
    this.controllerName = controllerName;
  }


  public ObjectMetaDataFields createable(Boolean createable) {
    
    this.createable = createable;
    return this;
  }

   /**
   * Get createable
   * @return createable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCreateable() {
    return createable;
  }


  public void setCreateable(Boolean createable) {
    this.createable = createable;
  }


  public ObjectMetaDataFields custom(Boolean custom) {
    
    this.custom = custom;
    return this;
  }

   /**
   * Get custom
   * @return custom
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getCustom() {
    return custom;
  }


  public void setCustom(Boolean custom) {
    this.custom = custom;
  }


  public ObjectMetaDataFields defaultValue(String defaultValue) {
    
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * Get defaultValue
   * @return defaultValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getDefaultValue() {
    return defaultValue;
  }


  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }


  public ObjectMetaDataFields defaultValueFormula(String defaultValueFormula) {
    
    this.defaultValueFormula = defaultValueFormula;
    return this;
  }

   /**
   * Get defaultValueFormula
   * @return defaultValueFormula
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getDefaultValueFormula() {
    return defaultValueFormula;
  }


  public void setDefaultValueFormula(String defaultValueFormula) {
    this.defaultValueFormula = defaultValueFormula;
  }


  public ObjectMetaDataFields defaultedOnCreate(Boolean defaultedOnCreate) {
    
    this.defaultedOnCreate = defaultedOnCreate;
    return this;
  }

   /**
   * Get defaultedOnCreate
   * @return defaultedOnCreate
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDefaultedOnCreate() {
    return defaultedOnCreate;
  }


  public void setDefaultedOnCreate(Boolean defaultedOnCreate) {
    this.defaultedOnCreate = defaultedOnCreate;
  }


  public ObjectMetaDataFields dependentPicklist(Boolean dependentPicklist) {
    
    this.dependentPicklist = dependentPicklist;
    return this;
  }

   /**
   * Get dependentPicklist
   * @return dependentPicklist
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDependentPicklist() {
    return dependentPicklist;
  }


  public void setDependentPicklist(Boolean dependentPicklist) {
    this.dependentPicklist = dependentPicklist;
  }


  public ObjectMetaDataFields deprecatedAndHidden(Boolean deprecatedAndHidden) {
    
    this.deprecatedAndHidden = deprecatedAndHidden;
    return this;
  }

   /**
   * Get deprecatedAndHidden
   * @return deprecatedAndHidden
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDeprecatedAndHidden() {
    return deprecatedAndHidden;
  }


  public void setDeprecatedAndHidden(Boolean deprecatedAndHidden) {
    this.deprecatedAndHidden = deprecatedAndHidden;
  }


  public ObjectMetaDataFields digits(Integer digits) {
    
    this.digits = digits;
    return this;
  }

   /**
   * Get digits
   * @return digits
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getDigits() {
    return digits;
  }


  public void setDigits(Integer digits) {
    this.digits = digits;
  }


  public ObjectMetaDataFields displayLocationInDecimal(Boolean displayLocationInDecimal) {
    
    this.displayLocationInDecimal = displayLocationInDecimal;
    return this;
  }

   /**
   * Get displayLocationInDecimal
   * @return displayLocationInDecimal
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getDisplayLocationInDecimal() {
    return displayLocationInDecimal;
  }


  public void setDisplayLocationInDecimal(Boolean displayLocationInDecimal) {
    this.displayLocationInDecimal = displayLocationInDecimal;
  }


  public ObjectMetaDataFields encrypted(Boolean encrypted) {
    
    this.encrypted = encrypted;
    return this;
  }

   /**
   * Get encrypted
   * @return encrypted
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getEncrypted() {
    return encrypted;
  }


  public void setEncrypted(Boolean encrypted) {
    this.encrypted = encrypted;
  }


  public ObjectMetaDataFields externalId(Boolean externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getExternalId() {
    return externalId;
  }


  public void setExternalId(Boolean externalId) {
    this.externalId = externalId;
  }


  public ObjectMetaDataFields extraTypeInfo(String extraTypeInfo) {
    
    this.extraTypeInfo = extraTypeInfo;
    return this;
  }

   /**
   * Get extraTypeInfo
   * @return extraTypeInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getExtraTypeInfo() {
    return extraTypeInfo;
  }


  public void setExtraTypeInfo(String extraTypeInfo) {
    this.extraTypeInfo = extraTypeInfo;
  }


  public ObjectMetaDataFields filterable(Boolean filterable) {
    
    this.filterable = filterable;
    return this;
  }

   /**
   * Get filterable
   * @return filterable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getFilterable() {
    return filterable;
  }


  public void setFilterable(Boolean filterable) {
    this.filterable = filterable;
  }


  public ObjectMetaDataFields filteredLookupInfo(String filteredLookupInfo) {
    
    this.filteredLookupInfo = filteredLookupInfo;
    return this;
  }

   /**
   * Get filteredLookupInfo
   * @return filteredLookupInfo
  **/
  @ApiModelProperty(required = true, value = "")

  public String getFilteredLookupInfo() {
    return filteredLookupInfo;
  }


  public void setFilteredLookupInfo(String filteredLookupInfo) {
    this.filteredLookupInfo = filteredLookupInfo;
  }


  public ObjectMetaDataFields formulaTreatNullNumberAsZero(Boolean formulaTreatNullNumberAsZero) {
    
    this.formulaTreatNullNumberAsZero = formulaTreatNullNumberAsZero;
    return this;
  }

   /**
   * Get formulaTreatNullNumberAsZero
   * @return formulaTreatNullNumberAsZero
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getFormulaTreatNullNumberAsZero() {
    return formulaTreatNullNumberAsZero;
  }


  public void setFormulaTreatNullNumberAsZero(Boolean formulaTreatNullNumberAsZero) {
    this.formulaTreatNullNumberAsZero = formulaTreatNullNumberAsZero;
  }


  public ObjectMetaDataFields groupable(Boolean groupable) {
    
    this.groupable = groupable;
    return this;
  }

   /**
   * Get groupable
   * @return groupable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getGroupable() {
    return groupable;
  }


  public void setGroupable(Boolean groupable) {
    this.groupable = groupable;
  }


  public ObjectMetaDataFields highScaleNumber(Boolean highScaleNumber) {
    
    this.highScaleNumber = highScaleNumber;
    return this;
  }

   /**
   * Get highScaleNumber
   * @return highScaleNumber
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getHighScaleNumber() {
    return highScaleNumber;
  }


  public void setHighScaleNumber(Boolean highScaleNumber) {
    this.highScaleNumber = highScaleNumber;
  }


  public ObjectMetaDataFields htmlFormatted(Boolean htmlFormatted) {
    
    this.htmlFormatted = htmlFormatted;
    return this;
  }

   /**
   * Get htmlFormatted
   * @return htmlFormatted
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getHtmlFormatted() {
    return htmlFormatted;
  }


  public void setHtmlFormatted(Boolean htmlFormatted) {
    this.htmlFormatted = htmlFormatted;
  }


  public ObjectMetaDataFields idLookup(Boolean idLookup) {
    
    this.idLookup = idLookup;
    return this;
  }

   /**
   * Get idLookup
   * @return idLookup
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getIdLookup() {
    return idLookup;
  }


  public void setIdLookup(Boolean idLookup) {
    this.idLookup = idLookup;
  }


  public ObjectMetaDataFields inlineHelpText(String inlineHelpText) {
    
    this.inlineHelpText = inlineHelpText;
    return this;
  }

   /**
   * Get inlineHelpText
   * @return inlineHelpText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getInlineHelpText() {
    return inlineHelpText;
  }


  public void setInlineHelpText(String inlineHelpText) {
    this.inlineHelpText = inlineHelpText;
  }


  public ObjectMetaDataFields label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public ObjectMetaDataFields length(Integer length) {
    
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getLength() {
    return length;
  }


  public void setLength(Integer length) {
    this.length = length;
  }


  public ObjectMetaDataFields mask(String mask) {
    
    this.mask = mask;
    return this;
  }

   /**
   * Get mask
   * @return mask
  **/
  @ApiModelProperty(required = true, value = "")

  public String getMask() {
    return mask;
  }


  public void setMask(String mask) {
    this.mask = mask;
  }


  public ObjectMetaDataFields maskType(String maskType) {
    
    this.maskType = maskType;
    return this;
  }

   /**
   * Get maskType
   * @return maskType
  **/
  @ApiModelProperty(required = true, value = "")

  public String getMaskType() {
    return maskType;
  }


  public void setMaskType(String maskType) {
    this.maskType = maskType;
  }


  public ObjectMetaDataFields name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ObjectMetaDataFields nameField(Boolean nameField) {
    
    this.nameField = nameField;
    return this;
  }

   /**
   * Get nameField
   * @return nameField
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getNameField() {
    return nameField;
  }


  public void setNameField(Boolean nameField) {
    this.nameField = nameField;
  }


  public ObjectMetaDataFields namePointing(Boolean namePointing) {
    
    this.namePointing = namePointing;
    return this;
  }

   /**
   * Get namePointing
   * @return namePointing
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getNamePointing() {
    return namePointing;
  }


  public void setNamePointing(Boolean namePointing) {
    this.namePointing = namePointing;
  }


  public ObjectMetaDataFields nillable(Boolean nillable) {
    
    this.nillable = nillable;
    return this;
  }

   /**
   * Get nillable
   * @return nillable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getNillable() {
    return nillable;
  }


  public void setNillable(Boolean nillable) {
    this.nillable = nillable;
  }


  public ObjectMetaDataFields permissionable(Boolean permissionable) {
    
    this.permissionable = permissionable;
    return this;
  }

   /**
   * Get permissionable
   * @return permissionable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getPermissionable() {
    return permissionable;
  }


  public void setPermissionable(Boolean permissionable) {
    this.permissionable = permissionable;
  }


  public ObjectMetaDataFields picklistValues(List<ObjectMetaDataPicklistValues> picklistValues) {
    
    this.picklistValues = picklistValues;
    return this;
  }

  public ObjectMetaDataFields addPicklistValuesItem(ObjectMetaDataPicklistValues picklistValuesItem) {
    this.picklistValues.add(picklistValuesItem);
    return this;
  }

   /**
   * Get picklistValues
   * @return picklistValues
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ObjectMetaDataPicklistValues> getPicklistValues() {
    return picklistValues;
  }


  public void setPicklistValues(List<ObjectMetaDataPicklistValues> picklistValues) {
    this.picklistValues = picklistValues;
  }


  public ObjectMetaDataFields polymorphicForeignKey(Boolean polymorphicForeignKey) {
    
    this.polymorphicForeignKey = polymorphicForeignKey;
    return this;
  }

   /**
   * Get polymorphicForeignKey
   * @return polymorphicForeignKey
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getPolymorphicForeignKey() {
    return polymorphicForeignKey;
  }


  public void setPolymorphicForeignKey(Boolean polymorphicForeignKey) {
    this.polymorphicForeignKey = polymorphicForeignKey;
  }


  public ObjectMetaDataFields precision(Integer precision) {
    
    this.precision = precision;
    return this;
  }

   /**
   * Get precision
   * @return precision
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getPrecision() {
    return precision;
  }


  public void setPrecision(Integer precision) {
    this.precision = precision;
  }


  public ObjectMetaDataFields queryByDistance(Boolean queryByDistance) {
    
    this.queryByDistance = queryByDistance;
    return this;
  }

   /**
   * Get queryByDistance
   * @return queryByDistance
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getQueryByDistance() {
    return queryByDistance;
  }


  public void setQueryByDistance(Boolean queryByDistance) {
    this.queryByDistance = queryByDistance;
  }


  public ObjectMetaDataFields referenceTargetField(String referenceTargetField) {
    
    this.referenceTargetField = referenceTargetField;
    return this;
  }

   /**
   * Get referenceTargetField
   * @return referenceTargetField
  **/
  @ApiModelProperty(required = true, value = "")

  public String getReferenceTargetField() {
    return referenceTargetField;
  }


  public void setReferenceTargetField(String referenceTargetField) {
    this.referenceTargetField = referenceTargetField;
  }


  public ObjectMetaDataFields referenceTo(List<String> referenceTo) {
    
    this.referenceTo = referenceTo;
    return this;
  }

  public ObjectMetaDataFields addReferenceToItem(String referenceToItem) {
    this.referenceTo.add(referenceToItem);
    return this;
  }

   /**
   * Get referenceTo
   * @return referenceTo
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getReferenceTo() {
    return referenceTo;
  }


  public void setReferenceTo(List<String> referenceTo) {
    this.referenceTo = referenceTo;
  }


  public ObjectMetaDataFields relationshipName(String relationshipName) {
    
    this.relationshipName = relationshipName;
    return this;
  }

   /**
   * Get relationshipName
   * @return relationshipName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public String getRelationshipName() {
    return relationshipName;
  }


  public void setRelationshipName(String relationshipName) {
    this.relationshipName = relationshipName;
  }


  public ObjectMetaDataFields relationshipOrder(String relationshipOrder) {
    
    this.relationshipOrder = relationshipOrder;
    return this;
  }

   /**
   * Get relationshipOrder
   * @return relationshipOrder
  **/
  @ApiModelProperty(required = true, value = "")

  public String getRelationshipOrder() {
    return relationshipOrder;
  }


  public void setRelationshipOrder(String relationshipOrder) {
    this.relationshipOrder = relationshipOrder;
  }


  public ObjectMetaDataFields restrictedDelete(Boolean restrictedDelete) {
    
    this.restrictedDelete = restrictedDelete;
    return this;
  }

   /**
   * Get restrictedDelete
   * @return restrictedDelete
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getRestrictedDelete() {
    return restrictedDelete;
  }


  public void setRestrictedDelete(Boolean restrictedDelete) {
    this.restrictedDelete = restrictedDelete;
  }


  public ObjectMetaDataFields restrictedPicklist(Boolean restrictedPicklist) {
    
    this.restrictedPicklist = restrictedPicklist;
    return this;
  }

   /**
   * Get restrictedPicklist
   * @return restrictedPicklist
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getRestrictedPicklist() {
    return restrictedPicklist;
  }


  public void setRestrictedPicklist(Boolean restrictedPicklist) {
    this.restrictedPicklist = restrictedPicklist;
  }


  public ObjectMetaDataFields scale(Integer scale) {
    
    this.scale = scale;
    return this;
  }

   /**
   * Get scale
   * @return scale
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getScale() {
    return scale;
  }


  public void setScale(Integer scale) {
    this.scale = scale;
  }


  public ObjectMetaDataFields searchPrefilterable(Boolean searchPrefilterable) {
    
    this.searchPrefilterable = searchPrefilterable;
    return this;
  }

   /**
   * Get searchPrefilterable
   * @return searchPrefilterable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getSearchPrefilterable() {
    return searchPrefilterable;
  }


  public void setSearchPrefilterable(Boolean searchPrefilterable) {
    this.searchPrefilterable = searchPrefilterable;
  }


  public ObjectMetaDataFields soapType(String soapType) {
    
    this.soapType = soapType;
    return this;
  }

   /**
   * Get soapType
   * @return soapType
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSoapType() {
    return soapType;
  }


  public void setSoapType(String soapType) {
    this.soapType = soapType;
  }


  public ObjectMetaDataFields sortable(Boolean sortable) {
    
    this.sortable = sortable;
    return this;
  }

   /**
   * Get sortable
   * @return sortable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getSortable() {
    return sortable;
  }


  public void setSortable(Boolean sortable) {
    this.sortable = sortable;
  }


  public ObjectMetaDataFields type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public ObjectMetaDataFields unique(Boolean unique) {
    
    this.unique = unique;
    return this;
  }

   /**
   * Get unique
   * @return unique
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getUnique() {
    return unique;
  }


  public void setUnique(Boolean unique) {
    this.unique = unique;
  }


  public ObjectMetaDataFields updateable(Boolean updateable) {
    
    this.updateable = updateable;
    return this;
  }

   /**
   * Get updateable
   * @return updateable
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getUpdateable() {
    return updateable;
  }


  public void setUpdateable(Boolean updateable) {
    this.updateable = updateable;
  }


  public ObjectMetaDataFields writeRequiresMasterRead(Boolean writeRequiresMasterRead) {
    
    this.writeRequiresMasterRead = writeRequiresMasterRead;
    return this;
  }

   /**
   * Get writeRequiresMasterRead
   * @return writeRequiresMasterRead
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getWriteRequiresMasterRead() {
    return writeRequiresMasterRead;
  }


  public void setWriteRequiresMasterRead(Boolean writeRequiresMasterRead) {
    this.writeRequiresMasterRead = writeRequiresMasterRead;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectMetaDataFields objectMetaDataFields = (ObjectMetaDataFields) o;
    return Objects.equals(this.aggregatable, objectMetaDataFields.aggregatable) &&
        Objects.equals(this.aiPredictionField, objectMetaDataFields.aiPredictionField) &&
        Objects.equals(this.autoNumber, objectMetaDataFields.autoNumber) &&
        Objects.equals(this.byteLength, objectMetaDataFields.byteLength) &&
        Objects.equals(this.calculated, objectMetaDataFields.calculated) &&
        Objects.equals(this.calculatedFormula, objectMetaDataFields.calculatedFormula) &&
        Objects.equals(this.cascadeDelete, objectMetaDataFields.cascadeDelete) &&
        Objects.equals(this.caseSensitive, objectMetaDataFields.caseSensitive) &&
        Objects.equals(this.compoundFieldName, objectMetaDataFields.compoundFieldName) &&
        Objects.equals(this.controllerName, objectMetaDataFields.controllerName) &&
        Objects.equals(this.createable, objectMetaDataFields.createable) &&
        Objects.equals(this.custom, objectMetaDataFields.custom) &&
        Objects.equals(this.defaultValue, objectMetaDataFields.defaultValue) &&
        Objects.equals(this.defaultValueFormula, objectMetaDataFields.defaultValueFormula) &&
        Objects.equals(this.defaultedOnCreate, objectMetaDataFields.defaultedOnCreate) &&
        Objects.equals(this.dependentPicklist, objectMetaDataFields.dependentPicklist) &&
        Objects.equals(this.deprecatedAndHidden, objectMetaDataFields.deprecatedAndHidden) &&
        Objects.equals(this.digits, objectMetaDataFields.digits) &&
        Objects.equals(this.displayLocationInDecimal, objectMetaDataFields.displayLocationInDecimal) &&
        Objects.equals(this.encrypted, objectMetaDataFields.encrypted) &&
        Objects.equals(this.externalId, objectMetaDataFields.externalId) &&
        Objects.equals(this.extraTypeInfo, objectMetaDataFields.extraTypeInfo) &&
        Objects.equals(this.filterable, objectMetaDataFields.filterable) &&
        Objects.equals(this.filteredLookupInfo, objectMetaDataFields.filteredLookupInfo) &&
        Objects.equals(this.formulaTreatNullNumberAsZero, objectMetaDataFields.formulaTreatNullNumberAsZero) &&
        Objects.equals(this.groupable, objectMetaDataFields.groupable) &&
        Objects.equals(this.highScaleNumber, objectMetaDataFields.highScaleNumber) &&
        Objects.equals(this.htmlFormatted, objectMetaDataFields.htmlFormatted) &&
        Objects.equals(this.idLookup, objectMetaDataFields.idLookup) &&
        Objects.equals(this.inlineHelpText, objectMetaDataFields.inlineHelpText) &&
        Objects.equals(this.label, objectMetaDataFields.label) &&
        Objects.equals(this.length, objectMetaDataFields.length) &&
        Objects.equals(this.mask, objectMetaDataFields.mask) &&
        Objects.equals(this.maskType, objectMetaDataFields.maskType) &&
        Objects.equals(this.name, objectMetaDataFields.name) &&
        Objects.equals(this.nameField, objectMetaDataFields.nameField) &&
        Objects.equals(this.namePointing, objectMetaDataFields.namePointing) &&
        Objects.equals(this.nillable, objectMetaDataFields.nillable) &&
        Objects.equals(this.permissionable, objectMetaDataFields.permissionable) &&
        Objects.equals(this.picklistValues, objectMetaDataFields.picklistValues) &&
        Objects.equals(this.polymorphicForeignKey, objectMetaDataFields.polymorphicForeignKey) &&
        Objects.equals(this.precision, objectMetaDataFields.precision) &&
        Objects.equals(this.queryByDistance, objectMetaDataFields.queryByDistance) &&
        Objects.equals(this.referenceTargetField, objectMetaDataFields.referenceTargetField) &&
        Objects.equals(this.referenceTo, objectMetaDataFields.referenceTo) &&
        Objects.equals(this.relationshipName, objectMetaDataFields.relationshipName) &&
        Objects.equals(this.relationshipOrder, objectMetaDataFields.relationshipOrder) &&
        Objects.equals(this.restrictedDelete, objectMetaDataFields.restrictedDelete) &&
        Objects.equals(this.restrictedPicklist, objectMetaDataFields.restrictedPicklist) &&
        Objects.equals(this.scale, objectMetaDataFields.scale) &&
        Objects.equals(this.searchPrefilterable, objectMetaDataFields.searchPrefilterable) &&
        Objects.equals(this.soapType, objectMetaDataFields.soapType) &&
        Objects.equals(this.sortable, objectMetaDataFields.sortable) &&
        Objects.equals(this.type, objectMetaDataFields.type) &&
        Objects.equals(this.unique, objectMetaDataFields.unique) &&
        Objects.equals(this.updateable, objectMetaDataFields.updateable) &&
        Objects.equals(this.writeRequiresMasterRead, objectMetaDataFields.writeRequiresMasterRead);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aggregatable, aiPredictionField, autoNumber, byteLength, calculated, calculatedFormula, cascadeDelete, caseSensitive, compoundFieldName, controllerName, createable, custom, defaultValue, defaultValueFormula, defaultedOnCreate, dependentPicklist, deprecatedAndHidden, digits, displayLocationInDecimal, encrypted, externalId, extraTypeInfo, filterable, filteredLookupInfo, formulaTreatNullNumberAsZero, groupable, highScaleNumber, htmlFormatted, idLookup, inlineHelpText, label, length, mask, maskType, name, nameField, namePointing, nillable, permissionable, picklistValues, polymorphicForeignKey, precision, queryByDistance, referenceTargetField, referenceTo, relationshipName, relationshipOrder, restrictedDelete, restrictedPicklist, scale, searchPrefilterable, soapType, sortable, type, unique, updateable, writeRequiresMasterRead);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectMetaDataFields {\n");
    sb.append("    aggregatable: ").append(toIndentedString(aggregatable)).append("\n");
    sb.append("    aiPredictionField: ").append(toIndentedString(aiPredictionField)).append("\n");
    sb.append("    autoNumber: ").append(toIndentedString(autoNumber)).append("\n");
    sb.append("    byteLength: ").append(toIndentedString(byteLength)).append("\n");
    sb.append("    calculated: ").append(toIndentedString(calculated)).append("\n");
    sb.append("    calculatedFormula: ").append(toIndentedString(calculatedFormula)).append("\n");
    sb.append("    cascadeDelete: ").append(toIndentedString(cascadeDelete)).append("\n");
    sb.append("    caseSensitive: ").append(toIndentedString(caseSensitive)).append("\n");
    sb.append("    compoundFieldName: ").append(toIndentedString(compoundFieldName)).append("\n");
    sb.append("    controllerName: ").append(toIndentedString(controllerName)).append("\n");
    sb.append("    createable: ").append(toIndentedString(createable)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    defaultValueFormula: ").append(toIndentedString(defaultValueFormula)).append("\n");
    sb.append("    defaultedOnCreate: ").append(toIndentedString(defaultedOnCreate)).append("\n");
    sb.append("    dependentPicklist: ").append(toIndentedString(dependentPicklist)).append("\n");
    sb.append("    deprecatedAndHidden: ").append(toIndentedString(deprecatedAndHidden)).append("\n");
    sb.append("    digits: ").append(toIndentedString(digits)).append("\n");
    sb.append("    displayLocationInDecimal: ").append(toIndentedString(displayLocationInDecimal)).append("\n");
    sb.append("    encrypted: ").append(toIndentedString(encrypted)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    extraTypeInfo: ").append(toIndentedString(extraTypeInfo)).append("\n");
    sb.append("    filterable: ").append(toIndentedString(filterable)).append("\n");
    sb.append("    filteredLookupInfo: ").append(toIndentedString(filteredLookupInfo)).append("\n");
    sb.append("    formulaTreatNullNumberAsZero: ").append(toIndentedString(formulaTreatNullNumberAsZero)).append("\n");
    sb.append("    groupable: ").append(toIndentedString(groupable)).append("\n");
    sb.append("    highScaleNumber: ").append(toIndentedString(highScaleNumber)).append("\n");
    sb.append("    htmlFormatted: ").append(toIndentedString(htmlFormatted)).append("\n");
    sb.append("    idLookup: ").append(toIndentedString(idLookup)).append("\n");
    sb.append("    inlineHelpText: ").append(toIndentedString(inlineHelpText)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    mask: ").append(toIndentedString(mask)).append("\n");
    sb.append("    maskType: ").append(toIndentedString(maskType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameField: ").append(toIndentedString(nameField)).append("\n");
    sb.append("    namePointing: ").append(toIndentedString(namePointing)).append("\n");
    sb.append("    nillable: ").append(toIndentedString(nillable)).append("\n");
    sb.append("    permissionable: ").append(toIndentedString(permissionable)).append("\n");
    sb.append("    picklistValues: ").append(toIndentedString(picklistValues)).append("\n");
    sb.append("    polymorphicForeignKey: ").append(toIndentedString(polymorphicForeignKey)).append("\n");
    sb.append("    precision: ").append(toIndentedString(precision)).append("\n");
    sb.append("    queryByDistance: ").append(toIndentedString(queryByDistance)).append("\n");
    sb.append("    referenceTargetField: ").append(toIndentedString(referenceTargetField)).append("\n");
    sb.append("    referenceTo: ").append(toIndentedString(referenceTo)).append("\n");
    sb.append("    relationshipName: ").append(toIndentedString(relationshipName)).append("\n");
    sb.append("    relationshipOrder: ").append(toIndentedString(relationshipOrder)).append("\n");
    sb.append("    restrictedDelete: ").append(toIndentedString(restrictedDelete)).append("\n");
    sb.append("    restrictedPicklist: ").append(toIndentedString(restrictedPicklist)).append("\n");
    sb.append("    scale: ").append(toIndentedString(scale)).append("\n");
    sb.append("    searchPrefilterable: ").append(toIndentedString(searchPrefilterable)).append("\n");
    sb.append("    soapType: ").append(toIndentedString(soapType)).append("\n");
    sb.append("    sortable: ").append(toIndentedString(sortable)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    unique: ").append(toIndentedString(unique)).append("\n");
    sb.append("    updateable: ").append(toIndentedString(updateable)).append("\n");
    sb.append("    writeRequiresMasterRead: ").append(toIndentedString(writeRequiresMasterRead)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

