/*
 * salesforce api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ObjectMetaDataUrls1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-01T18:23:34.688259300+08:00[Asia/Shanghai]")
public class ObjectMetaDataUrls1 {
  public static final String SERIALIZED_NAME_COMPACT_LAYOUTS = "compactLayouts";
  @SerializedName(SERIALIZED_NAME_COMPACT_LAYOUTS)
  private String compactLayouts;

  public static final String SERIALIZED_NAME_ROW_TEMPLATE = "rowTemplate";
  @SerializedName(SERIALIZED_NAME_ROW_TEMPLATE)
  private String rowTemplate;

  public static final String SERIALIZED_NAME_APPROVAL_LAYOUTS = "approvalLayouts";
  @SerializedName(SERIALIZED_NAME_APPROVAL_LAYOUTS)
  private String approvalLayouts;

  public static final String SERIALIZED_NAME_UI_DETAIL_TEMPLATE = "uiDetailTemplate";
  @SerializedName(SERIALIZED_NAME_UI_DETAIL_TEMPLATE)
  private String uiDetailTemplate;

  public static final String SERIALIZED_NAME_UI_EDIT_TEMPLATE = "uiEditTemplate";
  @SerializedName(SERIALIZED_NAME_UI_EDIT_TEMPLATE)
  private String uiEditTemplate;

  public static final String SERIALIZED_NAME_DESCRIBE = "describe";
  @SerializedName(SERIALIZED_NAME_DESCRIBE)
  private String describe;

  public static final String SERIALIZED_NAME_UI_NEW_RECORD = "uiNewRecord";
  @SerializedName(SERIALIZED_NAME_UI_NEW_RECORD)
  private String uiNewRecord;

  public static final String SERIALIZED_NAME_QUICK_ACTIONS = "quickActions";
  @SerializedName(SERIALIZED_NAME_QUICK_ACTIONS)
  private String quickActions;

  public static final String SERIALIZED_NAME_LAYOUTS = "layouts";
  @SerializedName(SERIALIZED_NAME_LAYOUTS)
  private String layouts;

  public static final String SERIALIZED_NAME_SOBJECT = "sobject";
  @SerializedName(SERIALIZED_NAME_SOBJECT)
  private String sobject;


  public ObjectMetaDataUrls1 compactLayouts(String compactLayouts) {
    
    this.compactLayouts = compactLayouts;
    return this;
  }

   /**
   * Get compactLayouts
   * @return compactLayouts
  **/
  @ApiModelProperty(required = true, value = "")

  public String getCompactLayouts() {
    return compactLayouts;
  }


  public void setCompactLayouts(String compactLayouts) {
    this.compactLayouts = compactLayouts;
  }


  public ObjectMetaDataUrls1 rowTemplate(String rowTemplate) {
    
    this.rowTemplate = rowTemplate;
    return this;
  }

   /**
   * Get rowTemplate
   * @return rowTemplate
  **/
  @ApiModelProperty(required = true, value = "")

  public String getRowTemplate() {
    return rowTemplate;
  }


  public void setRowTemplate(String rowTemplate) {
    this.rowTemplate = rowTemplate;
  }


  public ObjectMetaDataUrls1 approvalLayouts(String approvalLayouts) {
    
    this.approvalLayouts = approvalLayouts;
    return this;
  }

   /**
   * Get approvalLayouts
   * @return approvalLayouts
  **/
  @ApiModelProperty(required = true, value = "")

  public String getApprovalLayouts() {
    return approvalLayouts;
  }


  public void setApprovalLayouts(String approvalLayouts) {
    this.approvalLayouts = approvalLayouts;
  }


  public ObjectMetaDataUrls1 uiDetailTemplate(String uiDetailTemplate) {
    
    this.uiDetailTemplate = uiDetailTemplate;
    return this;
  }

   /**
   * Get uiDetailTemplate
   * @return uiDetailTemplate
  **/
  @ApiModelProperty(required = true, value = "")

  public String getUiDetailTemplate() {
    return uiDetailTemplate;
  }


  public void setUiDetailTemplate(String uiDetailTemplate) {
    this.uiDetailTemplate = uiDetailTemplate;
  }


  public ObjectMetaDataUrls1 uiEditTemplate(String uiEditTemplate) {
    
    this.uiEditTemplate = uiEditTemplate;
    return this;
  }

   /**
   * Get uiEditTemplate
   * @return uiEditTemplate
  **/
  @ApiModelProperty(required = true, value = "")

  public String getUiEditTemplate() {
    return uiEditTemplate;
  }


  public void setUiEditTemplate(String uiEditTemplate) {
    this.uiEditTemplate = uiEditTemplate;
  }


  public ObjectMetaDataUrls1 describe(String describe) {
    
    this.describe = describe;
    return this;
  }

   /**
   * Get describe
   * @return describe
  **/
  @ApiModelProperty(required = true, value = "")

  public String getDescribe() {
    return describe;
  }


  public void setDescribe(String describe) {
    this.describe = describe;
  }


  public ObjectMetaDataUrls1 uiNewRecord(String uiNewRecord) {
    
    this.uiNewRecord = uiNewRecord;
    return this;
  }

   /**
   * Get uiNewRecord
   * @return uiNewRecord
  **/
  @ApiModelProperty(required = true, value = "")

  public String getUiNewRecord() {
    return uiNewRecord;
  }


  public void setUiNewRecord(String uiNewRecord) {
    this.uiNewRecord = uiNewRecord;
  }


  public ObjectMetaDataUrls1 quickActions(String quickActions) {
    
    this.quickActions = quickActions;
    return this;
  }

   /**
   * Get quickActions
   * @return quickActions
  **/
  @ApiModelProperty(required = true, value = "")

  public String getQuickActions() {
    return quickActions;
  }


  public void setQuickActions(String quickActions) {
    this.quickActions = quickActions;
  }


  public ObjectMetaDataUrls1 layouts(String layouts) {
    
    this.layouts = layouts;
    return this;
  }

   /**
   * Get layouts
   * @return layouts
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLayouts() {
    return layouts;
  }


  public void setLayouts(String layouts) {
    this.layouts = layouts;
  }


  public ObjectMetaDataUrls1 sobject(String sobject) {
    
    this.sobject = sobject;
    return this;
  }

   /**
   * Get sobject
   * @return sobject
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSobject() {
    return sobject;
  }


  public void setSobject(String sobject) {
    this.sobject = sobject;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectMetaDataUrls1 objectMetaDataUrls1 = (ObjectMetaDataUrls1) o;
    return Objects.equals(this.compactLayouts, objectMetaDataUrls1.compactLayouts) &&
        Objects.equals(this.rowTemplate, objectMetaDataUrls1.rowTemplate) &&
        Objects.equals(this.approvalLayouts, objectMetaDataUrls1.approvalLayouts) &&
        Objects.equals(this.uiDetailTemplate, objectMetaDataUrls1.uiDetailTemplate) &&
        Objects.equals(this.uiEditTemplate, objectMetaDataUrls1.uiEditTemplate) &&
        Objects.equals(this.describe, objectMetaDataUrls1.describe) &&
        Objects.equals(this.uiNewRecord, objectMetaDataUrls1.uiNewRecord) &&
        Objects.equals(this.quickActions, objectMetaDataUrls1.quickActions) &&
        Objects.equals(this.layouts, objectMetaDataUrls1.layouts) &&
        Objects.equals(this.sobject, objectMetaDataUrls1.sobject);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compactLayouts, rowTemplate, approvalLayouts, uiDetailTemplate, uiEditTemplate, describe, uiNewRecord, quickActions, layouts, sobject);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectMetaDataUrls1 {\n");
    sb.append("    compactLayouts: ").append(toIndentedString(compactLayouts)).append("\n");
    sb.append("    rowTemplate: ").append(toIndentedString(rowTemplate)).append("\n");
    sb.append("    approvalLayouts: ").append(toIndentedString(approvalLayouts)).append("\n");
    sb.append("    uiDetailTemplate: ").append(toIndentedString(uiDetailTemplate)).append("\n");
    sb.append("    uiEditTemplate: ").append(toIndentedString(uiEditTemplate)).append("\n");
    sb.append("    describe: ").append(toIndentedString(describe)).append("\n");
    sb.append("    uiNewRecord: ").append(toIndentedString(uiNewRecord)).append("\n");
    sb.append("    quickActions: ").append(toIndentedString(quickActions)).append("\n");
    sb.append("    layouts: ").append(toIndentedString(layouts)).append("\n");
    sb.append("    sobject: ").append(toIndentedString(sobject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

