/*
 * salesforce api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ObjectInfoSobjects;

/**
 * ObjectInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-01T18:23:34.688259300+08:00[Asia/Shanghai]")
public class ObjectInfo {
  public static final String SERIALIZED_NAME_ENCODING = "encoding";
  @SerializedName(SERIALIZED_NAME_ENCODING)
  private String encoding;

  public static final String SERIALIZED_NAME_MAX_BATCH_SIZE = "maxBatchSize";
  @SerializedName(SERIALIZED_NAME_MAX_BATCH_SIZE)
  private Integer maxBatchSize;

  public static final String SERIALIZED_NAME_SOBJECTS = "sobjects";
  @SerializedName(SERIALIZED_NAME_SOBJECTS)
  private List<ObjectInfoSobjects> sobjects = new ArrayList<ObjectInfoSobjects>();


  public ObjectInfo encoding(String encoding) {
    
    this.encoding = encoding;
    return this;
  }

   /**
   * Get encoding
   * @return encoding
  **/
  @ApiModelProperty(required = true, value = "")

  public String getEncoding() {
    return encoding;
  }


  public void setEncoding(String encoding) {
    this.encoding = encoding;
  }


  public ObjectInfo maxBatchSize(Integer maxBatchSize) {
    
    this.maxBatchSize = maxBatchSize;
    return this;
  }

   /**
   * Get maxBatchSize
   * @return maxBatchSize
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getMaxBatchSize() {
    return maxBatchSize;
  }


  public void setMaxBatchSize(Integer maxBatchSize) {
    this.maxBatchSize = maxBatchSize;
  }


  public ObjectInfo sobjects(List<ObjectInfoSobjects> sobjects) {
    
    this.sobjects = sobjects;
    return this;
  }

  public ObjectInfo addSobjectsItem(ObjectInfoSobjects sobjectsItem) {
    this.sobjects.add(sobjectsItem);
    return this;
  }

   /**
   * Get sobjects
   * @return sobjects
  **/
  @ApiModelProperty(required = true, value = "")

  public List<ObjectInfoSobjects> getSobjects() {
    return sobjects;
  }


  public void setSobjects(List<ObjectInfoSobjects> sobjects) {
    this.sobjects = sobjects;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectInfo objectInfo = (ObjectInfo) o;
    return Objects.equals(this.encoding, objectInfo.encoding) &&
        Objects.equals(this.maxBatchSize, objectInfo.maxBatchSize) &&
        Objects.equals(this.sobjects, objectInfo.sobjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(encoding, maxBatchSize, sobjects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectInfo {\n");
    sb.append("    encoding: ").append(toIndentedString(encoding)).append("\n");
    sb.append("    maxBatchSize: ").append(toIndentedString(maxBatchSize)).append("\n");
    sb.append("    sobjects: ").append(toIndentedString(sobjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

